### ISSUE TITLE
dynamic tabbar content with update state event is laggy 

### ISSUE THREAD

**Issue by brambang** [satya164/react-native-tab-view#1039]
### Current behaviour
my apps has tabbar menu which showing all categories of product, and it will showing all product list in those category.
This menu called "fast shopping", so user can buy anything they need in this menu without switch to other page

<img src="https://user-images.githubusercontent.com/53509718/85361900-55805280-b547-11ea-9c8a-8f5fb3610990.png" width="360">

i created dynamic tabbar menu base on how many category is available from our API.
in this menu user can choose how many quantity they need and put in cart.
so i need update the content using update state, when user change quantity and update cart.

Ok, now we talk about the code,
i created renderScene variable in constructor: `this.renderScene = null;` to make this dynamic.
i created function which will update renderScene value to array with SceneMap
`this.renderScene = SceneMap(sceneRoutes);`

and here i called TabView component
```
<TabView
  lazy
  navigationState={{ index: this.state.tabIndex, routes: this.state.tabRoutes }}
  renderScene={this.renderScene}
  renderTabBar={this.renderTabBar}
  onIndexChange={(index) => this.setState({ tabIndex: index })}
/>
```

It succeed to showing the tabbar and it's content (like in screenshot)

### Expected behaviour

i have 2 problem:

#### Problem no 1
in this problem, i solved it with remove SceneMap.
in function i update renderScene value to array ~with sceneMap~
`this.renderScene = sceneRoutes;`

now here i called TabView component
```
<TabView
  lazy
  navigationState={{ index: this.state.tabIndex, routes: this.state.tabRoutes }}
  renderScene={(route) => {
  	return this.renderScene[route.route.key]();
  }}
  renderTabBar={this.renderTabBar}
  onIndexChange={(index) => this.setState({ tabIndex: index })}
/>
```

to make this still dynamic, im not use switch case.
instead i return the function which i created in this.renderScene array before.

It succeed to showing the tabbar and it's content, and page not re-render when user change category, change quantity, and put product in cart. 

#### Problem no 2
when user change quantity it would update state of quantity value, so it would re-render of quantity on intended product.
But the change not responsive, user cannot click + (plus) button simultaneously but have to wait to see the page re-render before he can click again.
I dont know why this happen, maybe someone could tell me why and how to solve it.

Other problem is very laggy when show and hide modal.

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | android
| react-native                 | 0.61.5
| react-native-tab-view        | 2.14.4
| react-native-gesture-handler | 1.6.0
| react-native-reanimated      | 1.7.0
| node                         | 12.7.0
| npm or yarn                  | 6.14.5

**Comment by brambang** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * ``
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.
> 
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `react-native-gesture-handler` (found: `1.6.0`, latest: `1.6.1`)
> * `react-native-reanimated` (found: `1.7.0`, latest: `1.9.0`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

im using expo framework then i eject to bare workflow.
react-native-gesture-handler and react-native-reanimated is used in Expo modules, i think is on their dependencies

**Comment by gostavee** [comment]
Happens with me too.
"react-native-tab-view": "^2.14.4"
