### ISSUE TITLE
Data not loading in first tab

### ISSUE THREAD

**Issue by har2008preet** [satya164/react-native-tab-view#1042]
**Current behaviour**

Data is not loading in first tab, but loading in other tabs

**Expected behaviour**

Data should load in first tab.

**What have you tried**

https://snack.expo.io/@har2008preet/reactnativetabviewbug

**Your Environment**

software | version
-- | --
android | 28.0.0
react-native | 0.61.5
react-native-tab-view | 2.14.4
react-native-gesture-handler | 1.6.1
react-native-reanimated | 1.9.0
node | 14.4.0
yarn | 1.5.1

**Comment by satya164** [comment]
This is because you're using `SceneMap` and passing state. You need to use `renderScene` directly: https://github.com/satya164/react-native-tab-view#renderscene-required
