### ISSUE TITLE
renderPager={props => <ScrollPager {...props} />} makes the horizontal scrolling not work on Android

### ISSUE THREAD

**Issue by azurechen** [satya164/react-native-tab-view#1043]
### Current behaviour

`renderPager={props => <ScrollPager {...props} />}` makes the horizontal scrolling unavailable on Android but work fine on iOS.
remove this prop and everything will be all right.

### Expected behaviour

Should be able to horizontally scroll pages.

### Code sample

```
<TabView
  renderPager={props => <ScrollPager { ...props }/>}
  // ...
/>
```

### What have you tried

Use `v2.14.3` and replace `ScrollPager` by `Pager` will work.
But `v2.14.4` remove the exporting of `Pager`.

### Your Environment

| software                     | version
| ---------------------------- | -------
| android               | 9.0
| react-native                 | 0.62.2
| react-native-tab-view        | 2.14.4
| react-native-gesture-handler | 1.6.0
| react-native-reanimated      | 1.9.0
| node                         | 8.0
| npm or yarn                  | yarn

**Comment by Aryk** [comment]
I'm experiencing the same thing. Curious if anyone else is experiencing this as well.

**Comment by westanvv** [comment]
Hello. I have the same issue. My environment is below:

software | version
-- | --
android | 10.0
react-native | 0.63.4
react-native-tab-view | 2.15.2
react-native-gesture-handler | 1.9.0
react-native-reanimated | 1.13.2
node | 15.5.0
yarn | 1.22.10
npm or yarn | yarn

Switching on `react-native-tab-view`: 2.14.3 and using `Pager` is working. Do you have any idea what is wrong with latest version?

**Comment by satya164** [comment]
Closing since this is an Android limitation.
