### ISSUE TITLE
The OnPress property in TouchableOpacity cannot be triggered when the page absolutely locates the element on the TAB

### ISSUE THREAD

**Issue by 1026576357** [satya164/react-native-tab-view#1048]
### Current behaviour

The OnPress property in TouchableOpacity cannot be triggered when the page absolutely locates the element on the TAB,
However, onPress can be triggered when the absolute positioning is not in the tabbed view.I think this is a tag level problem, but I don't know how to solve it
### Code sample

 {this.state.ofy>1?

                    <TouchableOpacity style={{zIndex:9999999999999999999999,position:'absolute',top:0,left:screenW-35,width:50,height:70,backgroundColor:'red'}} onPress={()=>{
                        console.log("123")
                        this.setState({
                                ofy:0
                            }
                        )}}>
                        <Text>首页</Text></TouchableOpacity>
                    :
                <ScrollView      //触底事件 这个很重要
                    // automaticallyAdjustContentInsets={false}
                    // showsVerticalScrollIndicator={false}
                >
                    <View style={{flex:0.5}}>

                        {/*/>*/}
                        <Swiper style={styles.wrapper} showsButtons={true} autoplay={true}>
                            <View style={styles.slide1}>
                                <Text style={styles.text}>Hello Swiper</Text>
                            </View>
                            <View style={styles.slide2}>
                                <Text style={styles.text}>Beautiful</Text>
                            </View>
                            <View style={styles.slide3}>
                                <Text style={styles.text}>And simple</Text>
                            </View>
                        </Swiper>
                    </View>

                </ScrollView>
                }
                <View style={{flex:20}}>

                <TabView
                    navigationState={this.state}
                    renderScene={SceneMap({
                        first: FirstRoute,
                        second:()=>(
                            <Item1  xx = {this.xx.bind(this)}></Item1>
                        ),
                        Three: ThreeRoute,
                        button:()=>(

                                <Button title={"测试"} onPress={    ()=>{
                                    console.log("test")
                                   }
                                }>测试</Button>

                        )
                    })}
                    onIndexChange={index => {
                        this.setState({index});
                        if(index>0){
                            this.setState({
                                ofy:34
                            })
                        }
                    }}
                    // initialLayout={{ width: Dimensions.get('window').width }}
                    // style={{width: Dimensions.get('window').width}}
                    bounces={true}
                    renderTabBar={props =>
                        <TabBar
                            {...props}
                            style={{
                                // backgroundColor: '#f3f0ef',
                                // shadowColor: '#d4d4d4',
                                // borderRadius:10,
                                // shadowOffset: {
                                //     width: 0,
                                //
                                // },
                                // shadowRadius: 0,
                                // marginTop: -5,
                                borderWidth:0
                            }}
                            getLabelText={({route}) => route.title}
                            labelStyle={{
                                fontFamily: 'PingFangSC-Regular',

                            }}
                            scrollEnabled={true}
                            tabStyle={{height: 43,width:screenW/4,backgroundColor:'white'}}
                            indicatorStyle={{backgroundColor: '#4a79e0'}}
                            activeColor={'#4a79e0'}
                            inactiveColor={'#666666'}

                        />
                    }
                />

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android              | android 
| react-native                |  0.62
| react-native-tab-view       | 2.14.4
| react-native-gesture-handler  | 1.5.2
| react-native-reanimated      | 1.4.0
| node                         | 11
| npm or yarn                  | npm

**Comment by Moji0098** [comment]
i have this problem too, 

    _"react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-reanimated": "^1.13.1",
    "react-native-tab-view": "^2.15.2",_

**Comment by Moji0098** [comment]
@1026576357  add SafeAreaView to your project

**Comment by tc9011** [comment]
same issue, any ideas?

```jsx
<SafeAreaView style={styles.wrapper}>
  <View style={styles.headerContainer}>
      <Text style={styles.title}>Press Me</Text>
      <TouchableWithoutFeedback>
          <Icon color={'#80868D'} size={18} name={'icon_notice'} />
      </TouchableWithoutFeedback>
  </View>

  <TabView
      navigationState={{ index, routes }}
      renderScene={renderScene}
      onIndexChange={setIndex}
      sceneContainerStyle={{ zIndex: 0 }}
      renderTabBar={renderTabBar}
      initialLayout={{ width: layout.width }}
  />

  <TouchableOpacity
      onPress={handlePress}
      style={[styles.addButton, { bottom: insets.bottom + 7 + 56 }]}>
      <Icon name={'btn_2'} />
  </TouchableOpacity>
</SafeAreaView>
``` 

```css
   wrapper: {
        paddingHorizontal: 20,
        backgroundColor: 'white',
        height: '100%',
    },
  addButton: {
        position: 'absolute',
        right: 16,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: COLORS.THEME_COLOR,
        width: 50,
        height: 50,
        borderRadius: 25,
    },
```
![image](https://user-images.githubusercontent.com/18380140/112488988-ff338f00-8db8-11eb-9a8d-b0cc90913d33.png)
