### ISSUE TITLE
how can i change the color of active tab bar and inactive tab bar color

### ISSUE THREAD

**Issue by govind1530** [satya164/react-native-tab-view#1051]
"react-native-tab-view": "^2.15.0",
         "react-native-gesture-handler": "^1.6.1",                 
          "react-native-reanimated": "^1.9.0",
     

                          <TabBar
                         activeColor={'#F5CB44'}
                        inactiveColor={'#F4F4F4'}
                        {...props}
                       indicatorStyle={{ 
                      backgroundColor: 'blue', 
                     height:3 }}
                     style={{ 
      	            backgroundColor: '#fff',
                    }}
                  renderLabel={({ route, focused, color }) => (
                 <Text style={{ 
                 fontSize: 18,
               fontWeight: 'bold', 
                margin: 10 }}>
               {route.title}
              </Text>
              )}
            />

I want to use different backgroundColor on different tab

**Comment by sa8ab** [comment]
You can create a custom tab bar for it, or you can change your active color based on the route you are in.

**Comment by ajithes1** [comment]
`<TabBar
           {...props}
           renderLabel={this._renderLabel}
   />`

`    _renderLabel = ({ route, focused }) => {
        if (focused) {
            return <Text style={{ color: 'black', fontSize: 15, minWidth: 100, textAlign: 'center' }}> {route.title} </Text>;
        }
        return <Text style={{ color: 'blue', fontSize: 15, minWidth: 100, textAlign: 'center' }}> {route.title} </Text>;
    }`
