### ISSUE TITLE
TextInput in Tab bug

### ISSUE THREAD

**Issue by stepanchenko26** [satya164/react-native-tab-view#1054]
Hi 2 all y'all. Sorry for my poor english. I got a trouble with TextInputs inside the Tab. When i press a key on keyboard when i enter the value in field, i got a bug: when i press the button, i got one symbol in field and keyboard got close. If i place TextInput outside the Tab everything works fine.

"expo": "~38.0.8",
"react-native-gesture-handler": "1.6.0",
"react-native-tab-view": "2.15.0",
"react-native-reanimated": "1.9.0"

**Comment by stepanchenko26** [comment]
I had to update versions of packeges, but i still got trouble

**Comment by Sanjay1416** [comment]
i have  "react-native-gesture-handler": "^1.7.0", but having same issue

**Comment by Sanjay1416** [comment]
i have  "react-native-gesture-handler": "^1.7.0",  when i type in text input one letter keyboard disappeared

**Comment by Sanjay1416** [comment]
There is any solution for this problem or not plz tell me

**Comment by Sanjay1416** [comment]
@satya164  plz tell me so that i can use this in my project i searched online but not found solution

**Comment by Sanjay1416** [comment]
@satya164  anyone here to help or not

**Comment by stepanchenko26** [comment]
> @satya164 anyone here to help or not

I had migrated to Swiper solution, all working fine

**Comment by asor7007** [comment]
same issue +1
anyone have solution?

If put `value` and `onChangeText` prop in `TextInput` the keyboard disappears whenever type.

**Comment by hogrid** [comment]
Same issue here =(

**Comment by supervons** [comment]
hello，everyone！
i use ref auto focus in the setState callback.
![image](https://user-images.githubusercontent.com/31637849/106576428-118f0a80-6578-11eb-985c-8c85fc0fb8ea.png)


it work for me.

**Comment by nicolak** [comment]
Same issue here =(

**Comment by asor7007** [comment]
This will work.

```javascript
const [index, setIndex] = useState(0);
const [routes] = useState([
  {key: 'one', title: 'tabOne'},
  {key: 'two', title: 'tabTwo'},
  {key: 'three', title: 'tabThree'},
]);

const [inputA, setInputA] = useState('');
const [inputB, setInputB] = useState('');
const [inputC, setInputC] = useState('');

// ~~~~
// ~~~~

const _renderTabs = ({route}) => {
  switch (route.key) {
    case 'one':
      return (
        <View><TextInput value={inputA} onChangeText={setInputA} /></View>
      )

    case 'two':
      return (
        <View><TextInput value={inputB} onChangeText={setInputB} /></View>
      )

    case 'three':
      return (
        <View><TextInput value={inputC} onChangeText={setInputC} /></View>
      )
  }
});

<TabView
  swipeEnabled={true}
  renderTabBar={() => null}
  navigationState={{index, routes}}
  renderScene={_renderTabs}
  onIndexChange={setIndex}
/>

```

**Comment by binumathew** [comment]
Any solution for this?

**Comment by binumathew** [comment]
> ```js
> <TabView
>   swipeEnabled={true}
>   renderTabBar={() => null}
>   navigationState={{index, routes}}
>   renderScene={_renderTabs}
>   onIndexChange={setIndex}
> />
> ```

It Showing a Black Screen for me

**Comment by nicolak** [comment]
Try [this.](https://github.com/satya164/react-native-tab-view/issues/1181#issuecomment-848083568)
It worked for me.

**Comment by satya164** [comment]
#1181

**Comment by sangolariel** [comment]
Any slolution?
