### ISSUE TITLE
Warning in bare minimum usage with React Navigation 5

### ISSUE THREAD

**Issue by sa8ab** [satya164/react-native-tab-view#1055]
### Current behaviour
Getting the following warning
![image](https://user-images.githubusercontent.com/59901734/88481940-2b89c980-cf13-11ea-98e9-683c28a4e7d6.png)

### Expected behaviour
Not to get the warning

### Code sample
Simple usage with react navigation
For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

### Your Environment

    "react-native-tab-view": "^2.15.
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^2.0.0-alpha.4",
    "react-native": "0.63.1",
    "@react-navigation/material-top-tabs": "^5.2.14",
    "@react-navigation/native": "^5.7.1",

**Comment by satya164** [comment]
https://github.com/satya164/react-native-tab-view/commit/73b9f63ddb046cd03a045eda1b5bb3c9ebbc1f09
