### ISSUE TITLE
Nesting swipeable component into a tab

### ISSUE THREAD

**Issue by Bayramito** [satya164/react-native-tab-view#1062]
Hello,

I'm using tabView somewhere in my project and i created 3 tabs. They are swipeable. And there is a carousel which has some images and it is also swipeable in the middle tab, but i cannot swipe between the images. It's swipes on the tabs not the images.

is there any solution for this?

**Comment by lander854** [comment]
same issue here

**Comment by VictorioMolina** [comment]
+1 with react-native-snap-carousel on Android.

I have seen the prop "swipeVelocityImpact" that determines how relevant is a velocity while calculating next position while swiping. Its default value is 0.2. Maybe this issue can be solved playing with this attribute.

**Comment by sa8ab** [comment]
You can pass properties to the PanGH of the tabview, give it a try by passing `minDeltaX` with value of like 10 or sth

**Comment by huunghi20061997** [comment]
You can use React-native Snap-Carousel for image list . Replace Flatlist, Scrollview on Carousel node_module them with import { ScrollView,FlatList } from "react-native-gesture-handler" . It's working @Bayramito
