### ISSUE TITLE
Release 2.14.2 breaks web support due to usage of non web supported react-native-reanimated v2

### ISSUE THREAD

**Issue by oste** [satya164/react-native-tab-view#1063]
### Current behaviour

Web is not supported in latest version due to the upgrade to 

### Expected behaviour

Web should remain supported or at least bump to a major version when breaking web support.

### Code sample

Specifically, this pull request https://github.com/satya164/react-native-tab-view/pull/1023

### What have you tried

yarn add `react-native-tab-view@2.14.2` resolves the issue for now. Unfortunately, Expo also seems confused so `expo install react-native-tab-view` installs the latest version

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | web
| react-native                 | 68
| react-native-tab-view        | 2.14.4
| react-native-gesture-handler | ~1.6.0
| react-native-reanimated      | ~1.9.0
| node                         | 14.7
| npm or yarn                  | yarn

**Comment by satya164** [comment]
It adds support for reanimated 2, doesn't require it.
