### ISSUE TITLE
Edit TSX files to create patch with patch-package not working

### ISSUE THREAD

**Issue by KoboBunny** [satya164/react-native-tab-view#1069]
**Problem**
I'm trying to apply a patch using patch-package after editing the TSX files in /src as opposed to the JS files in module /lib/module as it is much simpler to implement.

When I create my patch, the files in /lib/module don't change and the changes are also not reflected in my app when running on the simulator

**Environment**
react-native 0.63.0
patch-package 6.2.0
react-native-tab-view 2.15.1
react-native-gesture-handler 1.5.6
react-native-reanimated 1.7.0

**Question**
Am I missing a build or compile step to get react-native-tab-view to generate new JS files from the TSX files I created my patch for?

Any help would be greatly appreciated!

**Comment by satya164** [comment]
This is no longer applicable for React Native in latest version.
