### ISSUE TITLE
[FEATURE] pass ref to scene pages

### ISSUE THREAD

**Issue by hannojg** [satya164/react-native-tab-view#1070]
### Current behaviour

Currently, it appears to me that we are unable to pass refs to our scene pages. When accessing these refs, they are undefined.

### Expected behaviour

Passing refs to scene pages works.

### Code sample

```javascript
// In TabViewPage.js
const searchRef = useRef();

const renderScene = SceneMap({
  places: () => (
    <Searchpage
      ref={searchRef}
...

// accessing 
useEffect(() => {
  //⚠️: searchRef.current is undefined! 
  searchRef.current.search()
}, []);

```

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | both
| react-native                 | 0.63.2
| react-native-tab-view        |  2.15.1
| react-native-gesture-handler | 1.7.0
| react-native-reanimated      | 1.13.0
| node                         | 12

**Comment by ahtisham09** [comment]
did you find the solution

**Comment by satya164** [comment]
Please read this section https://github.com/satya164/react-native-tab-view#renderscene-required
