### ISSUE TITLE
Invalid Accessibility role Value: tab

### ISSUE THREAD

**Issue by ArminShahamati** [satya164/react-native-tab-view#1071]
hello dear friend 
after an update my Code I have this error :
Invalid Accessibility role Value: tab
but my code works correctly yesterday
![96acf3a3-e39d-4141-9191-82e8463ec878](https://user-images.githubusercontent.com/6270065/92277815-0ff9e180-ef09-11ea-8970-74ff9ad1ca9b.jpeg)

**Comment by TivanDev** [comment]
My package's Version

- "react-native-tab-view": "^2.15.1",
- "react-native-gesture-handler": "^1.3.0",
- "react-native-reanimated": "^1.1.0",

**Comment by TivanDev** [comment]
Everybody can help me?

**Comment by lucaashrq** [comment]
Same problem here, did you found a solution?

**Comment by muhsinaldemir** [comment]
Here's a solution for this problem in another thread:
https://github.com/satya164/react-native-tab-view/issues/955#issuecomment-632988806

**Comment by Vednus** [comment]
Still getting this error in 3.0.1
