### ISSUE TITLE
reload page when current tab changed

### ISSUE THREAD

**Issue by mtalhagaoglu** [satya164/react-native-tab-view#1077]
### Expected behaviour

I want to run a function when page focued and for that i am using navigation listener "focus" but with this tab-view listener these listeners doesnt trigger. how can i trigger a function or trigger listener when it is focused?

### What have you tried

I tried lazy param but its only trigger tab first time. second or more renders doesnt work as it shold be.

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |  andoid
| react-native                 | expo
| react-native-tab-view        | 2.15.1
| react-native-gesture-handler | 1.6.0
| react-native-reanimated      |1.7.0
| npm or yarn                  | npm

**Comment by TheRohitSharma** [comment]
I'm trying to figure out a solution to this as well. Wanting to fetch data only when the tab comes into focus.

**Comment by TheRohitSharma** [comment]
@mtalhagaoglu Just pass `lazy` to your react-native-tab-view component, and you can use useEffect as normal after that.

**Comment by mtalhagaoglu** [comment]
hi. thanks for you comment. i tried and it works but it works everytime it switches tab. for i example i have a,b and c tabs. whenever i navigate between tabs, 3 useEffects functions triggers at the same time.

**Comment by KhubaibQaiser** [comment]
Facing same issue. Want to trigger useEffect hook only for the currently focused tab. Any leads?

**Comment by wanderlust252** [comment]
any solution?

**Comment by mtalhagaoglu** [comment]
i ended with creating my own tab system (basicly switch case) . its easy actually you can do it also. i won't close the issue because it still exist in this lib
