### ISSUE TITLE
The link to the guide for additional steps for react-native-gesture-handler is outdated

### ISSUE THREAD

**Issue by daniel-addressya** [satya164/react-native-tab-view#1080]
`IMPORTANT: There are additional steps required for react-native-gesture-handler on Android after linking (for all React Native versions). Check the this guide to complete the installation.`

It's this link:
https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html

It says "Page not found".

**Comment by daniel-addressya** [comment]
The problem is in the README file in master (2.15.1).

**Comment by satya164** [comment]
Closing since we no longer use gesture handler.
