### ISSUE TITLE
When the content in ScrollPager exceeds, ScrollPager cannot scroll vertically

### ISSUE THREAD

**Issue by flycj** [satya164/react-native-tab-view#1089]
### Current behaviour

When the content in ScrollPager exceeds, ScrollPager cannot scroll vertically

### Expected behaviour

I hope that when the content in ScrollPager exceeds, ScrollPager can support vertical scrolling

### Code sample

```
const ProvinceRoute = () => {
  const provinces = Object.keys(areas);
  return (
    <View style={provinceStyles.root}>
      {provinces.map((item: string) => (
        <TouchableOpacity style={provinceStyles.item} key={item}>
          <Text>{item}</Text>
          <Icon name="arrow-right" size={20} />
        </TouchableOpacity>
      ))}
    </View>
  );
};

const CityRoute = () => {
  return (
    <View>
      <Text>test</Text>
    </View>
  );
};

const [routes] = React.useState([
    { key: 'province', title: 'Select' },
    { key: 'city', title: 'Select' },
  ]);
const renderScene = SceneMap({
    province: ProvinceRoute,
    city: CityRoute,
  });
const initialLayout = { width: Dimensions.get('window').width };
<TabView
        style={styles.tabView}
        navigationState={{ index, routes }}
        renderScene={renderScene}
        sceneContainerStyle={styles.sceneContainerStyle}
        renderPager={(props) => <ScrollPager overscroll {...props} />}
        renderTabBar={(props) => <TabBar style={styles.tabBar} tabStyle={styles.tabStyle} indicatorStyle={styles.indicatorStyle} labelStyle={styles.labelStyle} {...props} />}
        onIndexChange={setIndex}
        initialLayout={initialLayout}
        removeClippedSubviews
      />
const styles = StyleSheet.create({
  tabView: {
    flex: 0,
    height: 300,
  },
  sceneContainerStyle: {
  },
  tabBar: {
    backgroundColor: 'transparent',
  },
  tabStyle: {
    width: 'auto',
    paddingHorizontal: 0,
    marginRight: 30,
  },
  labelStyle: {
    color: '#333333',
  },
  indicatorStyle: {
    backgroundColor: '#ef4b4b',
    width: 50,
  },
});



```

### Screenshots (if applicable)
![error-demo](https://user-images.githubusercontent.com/5103045/96110315-436d5a00-0f12-11eb-8e55-088bfb873bcf.gif)

### What have you tried
I really don't know what to do. I think the role of ScrollPager should be scrollable? But no matter how I modify it, it will not scroll

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios               | 11
| expo                         |  39.0.3
| react-native                 | 0.63.3
| react-native-tab-view        | ^2.15.2
| react-native-gesture-handler | 1.8.0
| react-native-reanimated      | 1.13.1
| node                         | 10.16.3
| yarn                  |1.19.1

**Comment by flycj** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `expo`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.
> 
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `react-native` (found: `0.63.2`, latest: `0.63.3`)
> * `react-native-reanimated` (found: `1.13.0`, latest: `1.13.1`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

I have updated to the latest version, but this problem still exists

**Comment by lil12t** [comment]
still exists

```
{
   "react-native-reanimated":"^1.13.2",
   "react-native-tab-view":"^2.15.2",
   "react-native":"0.63.3"
}
```

**Comment by satya164** [comment]
Closing since we no longer use ScrollPager
