### ISSUE TITLE
TabBarIndicator custom color

### ISSUE THREAD

**Issue by atais** [satya164/react-native-tab-view#1100]
### Current behaviour

The "border" indicating active tab is fixed to:
```    
backgroundColor: '#ffeb3b',
```

https://github.com/satya164/react-native-tab-view/blob/main/src/TabBarIndicator.tsx

### Expected behaviour

I would like to customize it, 
preferably on `TabBar` level

### Code sample

```
<TabBar
    {...props}
    style={{backgroundColor: bgColor}} 
    tabBarIndicatorStyle={yourStyle}
    ...
    }}
  />
```

### What have you tried

Checking docs and code

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | android
| expo                         | no
| react-native                 | 0.63.3
| react-native-tab-view        | 2.15.2
| react-native-gesture-handler | 1.9.0
| react-native-reanimated      | 2.0.0-alpha.9.2
| node                         | 14.15
| npm or yarn                  | 6.14

**Comment by satya164** [comment]
https://github.com/satya164/react-native-tab-view#indicatorstyle
