### ISSUE TITLE
tab bar getting stuck in the middle after come back

### ISSUE THREAD

**Issue by felire** [satya164/react-native-tab-view#1101]
### Current behaviour

If I am on a tab, and then go to another screen and then come back to the tab again. The tab bar is in the middle, the content is also in the middle (two scenes are being shown)

### Expected behaviour

It should appear with the last tab selected

### Code sample

This is how I'm handling the TabBar:

```js
const TopTabBar = ({
  tabs,
  customTabBarProps = {
    equalWidthForEachTab: false,
    indicatorWidthAsLabelWidth: true,
  },
  primaryColor = Colors.Generic.black,
  secondaryColor,
  initialTab = 0,
  swipeEnabled = true,
  collapsibleInfo,
  onTabChange,
}: TopTabBarProps): JSX.Element => {
  const trackTabEvent = useTrackTabsEvents();
  const [index, setIndex] = React.useState(initialTab);
  const [routes] = React.useState(
    tabs.map(tab => ({
      accessibilityLabel: tab.accessibilityLabel,
      analyticsProps: tab.props?.analyticsProps,
      key: tab.key,
      title: tab.title,
    })),
  );
  const sceneMap = tabs.reduce(
    (acc, currentValue) => ({
      ...acc,
      [currentValue.key]: currentValue.screen,
    }),
    {},
  );
  const anyElementHasProps = tabs.some(tab => !!tab.props);
  const sceneMapHandlingProps = ({ route }: { route: Route }): JSX.Element => {
    const currentTab = tabs.find(tab => tab.key === route.key);
    const Component = currentTab?.screen as ComponentType<AnyProps>;
    return <Component {...currentTab?.props} />;
  };
  const renderScene = anyElementHasProps
    ? sceneMapHandlingProps
    : SceneMap(sceneMap);
  const secondaryColorToApply =
    secondaryColor ||
    (UtilColors.colorToDecimalRgbValues(primaryColor)[1] >=
    Constants.greenChannelLimit
      ? Colors.Generic.black
      : Colors.Generic.white);
  const handleIndexChange = (indexValue: number): void => {
    setIndex(indexValue);
    if (onTabChange) onTabChange(routes[indexValue].key, indexValue);
    accessibilityAnnounce('');
  };

  const isFocused = useIsFocused();

  useEffect(() => {
    if (isFocused) {
      trackTabEvent(Events.PageViewed, routes[index].analyticsProps);
    }
  }, [index, initialTab, isFocused, routes, trackTabEvent]);

  return (
    <TabView
      renderTabBar={renderCustomTabBar(customTabBarProps, {
        collapsibleInfo,
        primaryColor,
        secondaryColor: secondaryColorToApply,
        selectedKey: routes[index].key,
      })}
      swipeEnabled={swipeEnabled}
      navigationState={{ index, routes }}
      renderScene={renderScene}
      onIndexChange={handleIndexChange}
      initialLayout={{ width: Dimensions.get('window').width }}
    />
  );
};
```

### Screenshots (if applicable)

![Screen Shot 2020-12-01 at 13 00 44](https://user-images.githubusercontent.com/11776795/100767721-da19ab80-33d8-11eb-9230-ebcd6b3b7ee2.png)

### What have you tried

I tried to use just `SceneMap(sceneMap);` without sending props and the error is still happening. But it's hard to reproduce, it's not happening all the time. 

It's happening just on ios on this devices: 

iPhone 11 - iOS 14.1

iPhone XSMax - iOS 14.1

iPhone X - iOS 14.1

iPhone X - iOS 13.5.1

*Note: * Could not replicate on iPhone 8 - iOS 12.4.1

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | ios
| expo                         | no
| react-native                 | 0.61.5
| react-native-tab-view        | 2.15.2
| react-native-gesture-handler | 1.4.1
| react-native-reanimated      | 1.10.2
| node                         | 10.16.0
| npm or yarn                  | yarn

**Comment by agudeluca** [comment]
Im having the same issue!

**Comment by felire** [comment]
I tried with the last version of `react-native-gesture-handler` and `react-native-reanimated` and the issue is still happening. I can't upload `react-native` now

**Comment by felire** [comment]
I don't know if this matter but in the screen next to the tabs I'm using the native video player

**Comment by EmpireJones** [comment]
I've experienced the tab bar underline getting stuck in the wrong spot or between tabs, but it always only shows a single screen in my case.

It seems to be aggravated by heavy load on a screen. I reduced the frequency of this happening by disabling lazy screen loading.

**Comment by felire** [comment]
I fixed the issue using the `ScorllPager` on `renderPager` only for ios
