### ISSUE TITLE
SceneView - Warning: Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by EmpireJones** [satya164/react-native-tab-view#1103]
### Current behaviour

On hot reload, I'm getting a warning about setting state on an unmounted component

### Expected behaviour

Not to get the warning

### Code sample

It's caused by this code:
https://github.com/satya164/react-native-tab-view/blame/89280e1ee80adb97f7972656de26bf9295f63ec8/src/SceneView.tsx#L54

`setTimeout(() => this.setState({ loading: false }), 0);
`

The setState runs without checking that the component is still mounted. In this case, the component must be unmounting right after being mounted, as that timeout is zero, which should happen pretty quickly.

### What have you tried

Adding a check to ensure that the component is mounted fixes the warning.
```
setTimeout(() => {
        if (!this.unmounted) {
          this.setState({
            loading: false
          });
        }
      }, 0);
```

```
  componentWillUnmount() {
    this.unmounted = true;
    this.props.removeListener('enter', this.handleEnter);
  }
```

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | android q
| expo                         | N/A
| react-native                 | 0.63.3
| react-native-tab-view        | 2.15.2
| react-native-gesture-handler | 1.6.1
| react-native-reanimated      | 1.8.0
| node                         | v14.3.0
| npm or yarn                  | npm 6.14.9

**Comment by EmpireJones** [comment]
Yes; same behavior with 2.15.2. I'm not using expo.

**Comment by MandoMG** [comment]
I'm getting this warning while running tests. I'm using:

- React Native: 0.63.3
- react-native-tab-view: 2.12.5
- node: 12.18.2
- npm: 6.14.0

**Comment by toytonic** [comment]
Same here. Run into it while writing integration tests

**Comment by Saad-Bashar** [comment]
Same issue. I am showing a loader while data fetch and then show the tabview. But it gives me this warning, while adding the tabview without any loader seems to be okay.

**Comment by bryce0516** [comment]
Same here
