### ISSUE TITLE
[Question] Does it work with REA v2?

### ISSUE THREAD

**Issue by nelsonprsousa** [satya164/react-native-tab-view#1113]
Hi @satya164,
I am currently migrating from react-navigation to react-native-navigation and just noticed that it does not support top bars by default, so I searched a little bit and found out this library.

Does it work with the new react-native-reanimated v2?

Thank you for your amazing work 😎

**Comment by martinezguillaume** [comment]
I was not able to make it work with reanimated 2 with the simple example from the doc :'(

The app crash instantly with this error:
```
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[REACondNode beginContext:prevCallID:]: unrecognized selector sent to instance 0x60000041afd0'
```

**Comment by nelsonprsousa** [comment]
Closing.

The reanimated dependency was removed by @satya164 (release 3.0.0: https://github.com/satya164/react-native-tab-view/releases/tag/v3.0.0)

**Comment by jp928** [comment]
@nelsonprsousa Do you have any idea why this library move away from reanimated?

**Comment by nelsonprsousa** [comment]
> @nelsonprsousa Do you have any idea why this library move away from reanimated?

Yes, check https://twitter.com/satya164/status/1369344748620836867 and https://twitter.com/satya164/status/1369344244608098307 tweets from @satya164 explaining why.

That being said, we upgraded to 3.0.0 but reverted because the tab animation is lagging for whatever reason with 3.0.0.
