### ISSUE TITLE
TabBar Indicator animation dosen't match with TabBar

### ISSUE THREAD

**Issue by jscheol** [satya164/react-native-tab-view#1119]
### Current behaviour

After upgraded Expo version to 40, when I scrolling tabbar then indicator dosen't match with Tabbar and press tab indicator position is move wrong position.

It's ok not use scrollEnabled, but using 

### Expected behaviour

1. Scrolling Tabs, indicator also scroll too.
2. Press tab, indicator moving correct position

### Code sample

```javascript
import React, { useState } from "react";
import { SafeAreaView, View } from "react-native";
import { TabBar, TabView } from "react-native-tab-view";

export default function App() {
  const [index, setIndex] = useState(0);
  const [routes] = useState([
    { key: "popular", title: "TAB1" },
    { key: "bookmark", title: "TAB2" },
    { key: "end", title: "TAB3" },
    { key: "recent", title: "TAB4" },
    { key: "reward", title: "TAB5" },
  ]);

  const renderScene = () => (
    <View style={{ backgroundColor: `rgb(${Math.random()*255},${Math.random()*255},${Math.random()*255})`, width: "100%", height: "100%" }} />
  );

  return (
    <SafeAreaView style={{flex:1}}>
        <View style={{flex:1}}>
          <TabView
            navigationState={{ index, routes }}
            renderScene={renderScene}
            onIndexChange={setIndex}
            renderTabBar={(props) => <TabBar {...props} scrollEnabled/>}
            lazy
          />
        </View>
    </SafeAreaView>
  );
}
```

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/72911359/105934433-84d5df80-6093-11eb-9d57-3462459dcf34.png)

### What have you tried

I think it's related with react-native-reanimated. because it was correct positioning before upgrade expo to v40

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | ios
| expo                         | 40.0.0
| react-native                 |0.63.2
| react-native-tab-view        |2.15.2
| react-native-gesture-handler |1.8.0
| react-native-reanimated      |1.13.2
| node                         |10.17.0
| npm or yarn                  | yarn 1.22.5

**Comment by gauravroyzz** [comment]
there's still an issue

**Comment by tasugi** [comment]
I have used  @react-navigation/material-top-tabs, so used tab view indirectly and faced an similar problem. But after upgrading tab view to v3, the problem disappeared.

**Comment by yamgemy** [comment]
I had same problem, finally fixed by adding `tabStyle` as prop of`TabBar`, width should be the same your custom `renderLabel` (or/and `TabBarItem` if you have any) and that of the indicator (via `indicatorStyle`)

```
const renderTabBar = (props) => {
    return (
       <TabBar
          tabStyle={{width: 123} //<----This aligns indicator scroll position according to custom tab button width
          scrollEnabled={true}
          indicatorStyle={{width: 123} //<---same width as tab button
          {...props}
          renderLabel={({ route, focused, color }) => (
            <View style={{width: 123}> //<--also same width as tab button
              <Text
                {yourTabLabelHere}
              </Text>
            </View>
          )}
        />
    )
}
 ```
