### ISSUE TITLE
Header swipeable.

### ISSUE THREAD

**Issue by YevheniiShabelnykkk** [satya164/react-native-tab-view#1121]
Hello guys!

Do you know how can I do the same swipe behavior with animation for the header?

For example, make the swipeable green area in the header(attached image).

<img width="358" alt="Screenshot 2021-01-28 at 17 28 30" src="https://user-images.githubusercontent.com/53472115/106160397-74eef600-618e-11eb-8ad0-ad1a1ad9cb21.png">

react-native - 0.61.5
react-native-tab-view - 2.14.4
react-native-gesture-handler - 1.6.1
react-native-reanimated - 1.8.0

**Comment by opensw** [comment]
Same here. Did you find a solution?

Version packages:
- react-native 0.64.0
- react-native-tab-view 3.0.1
- react-native-gesture-handler 1.10.3
- react-native-reanimated 1.13.3

Thank you

**Comment by YevheniiShabelnykkk** [comment]
Didn't.

**Comment by opensw** [comment]
I have found a workaround, it is not the best one but you just need the required area to be represented by a component with the style `{position: "absolute", top: ..., left: ..., right: ..., bottom: ...}`. The trick is the `position: "absolute"` related to the parent, you can also add your margins and whatever you need in your style, with `top, left, right, bottom` you set the position of your component. 

You need to add this component to each page of the tab view (the page reppresents your parent), my component is just a simple button
