### ISSUE TITLE
facing issue when generate dyanmic routes

### ISSUE THREAD

**Issue by vikas-sonwani** [satya164/react-native-tab-view#1127]
### Expected behaviour

     const getNewRoute = cat =>{
                let rout= [];
                cat.forEach(item=>{
                      rout.push({key:item.key,title:item.title})
                })
                return rout;
          }
    const genScene = cat =>{
                let scene = []
                cat.forEach(item =>{
                     var c = item.key
                     scene.push( () => <View style={[styles.scene, { backgroundColor: '#fff',flexDirection:'row' }]} >
                            <ProductsList props={props} products={item.products} showProduct={showProduct} /> 
                                            
                      </View>)
                })
                return scene 
          }
      const genSceneMap = (cat,rr) =>{
            let map = {};
            cat.forEach((item,index) =>{
                  map[item.key] = rr[index] 
            })
            return map;
      }
      const getNewRoute = cat =>{
            let rout= [];
            cat.forEach(item=>{
                  rout.push({key:item.key,title:item.title})
            })
            return rout;
      }

For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

### Screenshots (if applicable)

![WhatsApp Image 2021-02-12 at 12 25 10 PM](https://user-images.githubusercontent.com/16484964/107761900-2591f380-6d52-11eb-9abf-0ffaf6f6fc3e.jpeg)

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |
| expo                         |
| react-native                 |
| react-native-tab-view        |
| react-native-gesture-handler |
| react-native-reanimated      |
| node                         |
| npm or yarn                  |

**Comment by Saad-Bashar** [comment]
Were you able to solve this  @vikas-sonwani ?

**Comment by vikas-sonwani** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `react-native`
> * `react-native-tab-view`
> * `react-native-gesture-handler`
> * `react-native-reanimated`
> * `expo`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.



> Couldn't find version numbers for the following packages in the issue:
> 
> * `react-native`
> * `react-native-tab-view`
> * `react-native-gesture-handler`
> * `react-native-reanimated`
> * `expo`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.
> * `react-native`
> * `react-native-tab-view`
> * `react-native-gesture-handler`
> * `react-native-reanimated`
> * `expo`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.


> * "react-native": "0.63.4",
> *  "react-native-tab-view": "^2.15.2",
> * "react-native-gesture-handler": "^1.9.0",
> * "react-native-reanimated": "^1.13.2",
> * `react-native-cli`
>  android
