### ISSUE TITLE
[v3][iOS] Tab changes twice with a quick swipe

### ISSUE THREAD

**Issue by ahce** [satya164/react-native-tab-view#1139]
### Current behaviour

![tabview-bug](https://user-images.githubusercontent.com/12452003/110568323-9221c780-8131-11eb-8121-7d7d5a826b50.gif)

### Expected behaviour

Normal tab change.

### Code sample

```
import React, { useState } from 'react';
import { StyleSheet, View, Text } from 'react-native';
import { SceneMap, TabView } from 'react-native-tab-view';

const styles = StyleSheet.create({
  scene: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 40
  },
  text: {
    fontSize: 24,
    lineHeight: 32,
    marginVertical: 2,
    letterSpacing: 0
  }
});

const Component1 = () => (
  <View style={styles.scene}>
    <Text style={styles.text}>React</Text>
  </View>
);

const Component2 = () => (
  <View style={styles.scene}>
    <Text style={styles.text}>Native</Text>
  </View>
);

const Demo = () => {
  const [navigationState, setNavigationState] = useState({
    index: 0,
    routes: [
      {
        key: 'react',
        title: 'Native'
      },
      {
        key: 'native',
        title: 'React'
      }
    ]
  });

  const renderScene = SceneMap({
    react: Component1,
    native: Component2
  });

  return (
    <TabView
      {...{ navigationState, renderScene }}
      onIndexChange={(index) => {
        setNavigationState((s) => ({ ...s, index }));
      }}
    />
  );
};

export default Demo;
```

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios               | iOS 13.5
| expo                         | none
| react-native                 | 0.63.4
| react-native-tab-view        | 3.0.0
| react-native-pager-view      | 5.0.12
| node                         | 14.16.0
| npm                  | 6.14.11

**Comment by kamui545** [comment]
@ahce Try upgrading react-native-pager-view to the latest release, it seems to be fixed thanks to https://github.com/callstack/react-native-pager-view/pull/356
