### ISSUE TITLE
Jest crashes with "SceneMap not found" error

### ISSUE THREAD

**Issue by kckunal2612** [satya164/react-native-tab-view#1141]
### Current behaviour

I want to test `react-native-tab-view` in one of my integration tests, using `react-native-testing-library`, on a component that has a `TabView` with 2 tabs. When I run the test, I get the following error -

`TypeError: react_native_tab_view_1.SceneMap is not a function`

### Expected behaviour

I want to test interactions on the different scenes, so it's necessary, that I can access all components in the rendered scenes.

### Code sample

```tsx
const renderScene = SceneMap({
    tab_primary: PrimaryTab,
    tab_secondary: SecondaryTab,
  });

  return (
    <ComponentNavigationContext.Provider value={navigation}>
      <TopTabBar
        navigationState={{ index, routes }}
        renderScene={renderScene}
        onIndexChange={setIndex}
      />
    </ComponentNavigationContext.Provider>
  );
};
```

### What have you tried

I've tried passing a mock renderScene function but that doesn't help.

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | N/A
| react-native                 | 0.63.4
| react-native-tab-view        | 2.15.2
| node                         | 15.2.1
| npm or yarn                  | 7.0.10

**Comment by AjmalTTN** [comment]
Mock the library like this:

```
import {View as mockView} from 'react-native';

jest.mock('react-native-tab-view', () => ({
  TabBar: mockView,
  TabView: mockView,
  SceneMap: jest.fn(),
}));
```
