### ISSUE TITLE
Crash with react-native-tab-view 3.0.0 and react-native 0.61.5

### ISSUE THREAD

**Issue by nromptea42** [satya164/react-native-tab-view#1143]
### Current behaviour

Upgrading from 2.5.x to 3.0.0 requires you to have react-native > 0.63.  
Otherwise it can crash when using non-custom `TabBarItem` because of the replacement of `TouchableItem` by `PlatformPressable` that requires `Pressable` from `react-native`.

### Expected behaviour

Maybe add a disclaimer in the README.md like this :

| React Native version | Supporting react-native-tab-view version |
|-------------------------|-------------------------------------------------------|
| < 0.63 | <= 2.5.2 |

**Comment by Aliakwe** [comment]
Having same issues??

**Comment by Aliakwe** [comment]
I am having same issue.

Is there any solution for this yet??

**Comment by Return-1** [comment]
I can confirm this

**Comment by patrickleemsantos** [comment]
Im currently experiencing this issue too.

**Comment by okwasniewski** [comment]
This got mereged, closing this.
