### ISSUE TITLE
[V3] RTL Gesture switch issue

### ISSUE THREAD

**Issue by kashmiry** [satya164/react-native-tab-view#1149]
### Current behaviour
![RTL issue](https://media.giphy.com/media/xY44WdvGF1ysNJFmbr/giphy.gif)
Tabs gestures switch on opposite direction in RTL, on LTR it works fine.

### Expected behaviour
Tabs switch normally, like in previous versions.

### Environment

Software | Version
------------ | -------------
react | 16.13.1
react-native | 0.63.4
react-native-tab-view | 3.0.0
react-native-pager-view | 5.1.1

**Comment by chybisov** [comment]
I have the same issue. @satya164 could you please help?

**Comment by satya164** [comment]
Please don't ping me. I'll take a look when I have free time, and you'll see updates on the issue.

**Comment by RZsam** [comment]
faced the same issue

**Comment by mehthabux** [comment]
any update on this issue ? , im also facing this issue

**Comment by aleppos** [comment]
@satya164 this issue has been resolved with react-native-pager-view@5.3.2, I think you can marked as resolved if you like.

**Comment by theMasix** [comment]
I have the same issue now!
@aleppos How is it possible? :)

Do you set `layoutDirection` prop to `rtl` on the `TabView` component?

Software | Version
-- | --
react-native | 0.63.4
react-native-tab-view | **3.1.1**
react-native-pager-view | **5.4.9**
