### ISSUE TITLE
Custom tab bar not scrollable

### ISSUE THREAD

**Issue by mohamed-ikram** [satya164/react-native-tab-view#1151]
### Current behavior
Hai, I have created a custom tab bar that is not scrollable if I add scroll view UI is breaking, and when I use view it's not scrollable.

### Expected behavior
what I need is the default behavior of react-native-tabview like when I swipe render scene it should scroll to the respective tab and the tab bar should be scrollable.

### Code sample

**rendertab** 

`_renderTabBar = (props) => {
    return (
      <View style={styles.tabBar}>
        {props.navigationState.routes.map((route, i) => {
          return (
            <TouchableOpacity
              style={{
                ...styles.tabItem,
                backgroundColor:
                  this.state.index === i ? AppColor.blue : AppColor.lightGrey1,
              }}
              onPress={() => this.setState({ index: i })}
            >
              <Animated.Text
                style={{
                  color:
                    this.state.index === i ? AppColor.white : AppColor.darkGrey,
                }}
              >
                {route.title}
              </Animated.Text>
            </TouchableOpacity>
          );
        })}
      </View>
    );
  };`

**main render**

`<View style={{ flex: 1, backgroundColor: "white" }}>
        <Text> textInComponent </Text>
        <Button title="add tab" onPress={() => this.addTabs()} />
        <TabView
          navigationState={this.state}
          renderScene={this.renderScene}
          renderTabBar={this._renderTabBar}
          onIndexChange={(index) => this.setState({ index })}
          initialLayout={{ width: Dimensions.get("window").width }}
        />
      </View>`

**styles**

`const styles = StyleSheet.create({
  tabbar: {
    backgroundColor: "transparent",
  },
  label: {
    fontSize: 16,
    fontFamily: "Roboto-Medium",
  },
  indicator: {
    backgroundColor: "#ffffff",
  },
  tabBar: {
    // flex: 1,
    flexDirection: "row",
    width: Dimensions.get("window").width,
  },
  tabItem: {
    // flexGrow: 1,
    alignItems: "center",
    paddingHorizontal: 24,
    paddingVertical: 16,
    marginRight: 20,
    marginTop: 10,
  },
});`

### Screenshots (if applicable)

![Screenshot_20210316-211049](https://user-images.githubusercontent.com/62332326/111337713-50969c80-869c-11eb-91a3-5e026866637f.jpg)

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |
| expo                         |
| react-native         ^0.63.3        |
| react-native-tab-view     ^2.14.4   |
| react-native-pager-view      |
| node                         |
| npm or yarn                  |

**Comment by thedarkcder** [comment]
i have the same issue - i have copied the example that is in the example folder - however I have maybe 20 tabs. i can select them going side to side but the  tab view does not change.

`  renderTabBar = (props) => (
    <TabBar
      {...props}
      scrollEnabled
      indicatorStyle={styles.indicator}
      style={styles.tabbar}
      tabStyle={styles.tab}
      labelStyle={styles.label}
    />
  );
`


tab view

`
  <TabView  
          navigationState={this.state.navigationState}
          renderScene={this._renderScene}
          renderTabBar={this.renderTabBar}
          onIndexChange={this._handleIndexChange}
        />
`
react-native: 0.63.4, 
react-native-tab-view: 3.0.0


Any ideas?

**Comment by mohamed-ikram** [comment]
@thedarkcder  can u share more details I cant understand the problem from the code u shared

**Comment by MicaelRodrigues** [comment]
@mohamed-ikram I'have the same problem, i cannot scroll if i have a custom tab component like this:

<img width="732" alt="Screen Shot 2021-12-21 at 15 33 12" src="https://user-images.githubusercontent.com/796443/146956339-96fea83e-e667-481e-b8e9-1e7eec737482.png">

**Comment by cianyastone** [comment]
@mohamed-ikram Sorry, not for answering the question, but can I ask for your full codes of the screenshot?
I'm in the problem of building a tab like that:( 
(A tab which can add tab by pressing the button)
