### ISSUE TITLE
How to customise TabBar width for Tablets?

### ISSUE THREAD

**Issue by vikrantnegi** [satya164/react-native-tab-view#1152]
### Current behaviour
Need to customize the tababr design on the tablets. Currently, they stretch full width.

### Expected behaviour
I want the TabBar to have the design as follows: 

<img width="1061" alt="Screenshot 2021-03-17 at 10 24 38 AM" src="https://user-images.githubusercontent.com/3294287/111417206-5ecfd180-870b-11eb-8c16-ecae3927e6e3.png">

### Code sample
```js
<TabBar
    {...props}
    indicatorStyle={{backgroundColor: colors.coolBlue, height: 5}}
    style={styles.tabBar}
    inactiveColor={colors.greyishBrown}
    activeColor={colors.violet}
    tabStyle={{paddingVertical: 15}}
    renderLabel={({route, focused, color}) => {
      const labelColor = focused ? colors.violet : colors.warmGrey;
      return (
        <Text style={[{color: labelColor}, styles.tabBarLabel]}>
          {route.title}
        </Text>
      );
    }}
  />
```

### What have you tried
I've tried to use different props available like `tabStyle`, `contentContainerStyle `  and `style` to achieve the desired design but I'm not able to replicate the same.

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | iPad
| react-native                 | 0.63.4
| react-native-tab-view        | 2.15.2
| node                         |  v15.8.0
| npm or yarn                  | yarn

**Comment by oliveirasWell** [comment]
@vikrantnegi did you find any solution?

**Comment by vikrantnegi** [comment]
@oliveirasWell No, I didn't find any solution yet.
