### ISSUE TITLE
unmountonblur

### ISSUE THREAD

**Issue by anandchakru** [satya164/react-native-tab-view#1155]
### Current behavior
unmountonblur is only available in [bottom-tab-nav](https://reactnavigation.org/docs/bottom-tab-navigator/#unmountonblur)
### Expected behavior
Mave unmountonblur available in [material-top-tab-nav](https://reactnavigation.org/docs/material-top-tab-navigator/#options) also

### What have you tried
n/a
### Your Environment

| software                     | version
| ---------------------------- | -------
| node                         | v15.11.0
| yarn                  | 1.22.10
| react-native                  | 0.64.0
| react-native-tab-view                  | 5.3.14
| react-native-pager-view                  | 5.0.11

**Comment by satya164** [comment]
Please open issues related to React Navigation in React Navigation's channels.

**Comment by anandchakru** [comment]
> Please open issues related to React Navigation in React Navigation's channels.

..and which repo/channel is that exactly - not sure how you have organized the modules.
