### ISSUE TITLE
[3.x.x] UI thread drop when tab changing 

### ISSUE THREAD

**Issue by Waqas-Jani** [satya164/react-native-tab-view#1160]
Hi, The previous version worked perfect, no UI thread dropped.  but in latest version, i notice this issue.
### Current behaviour
 I'm notice that when tab change , the UI thread dropped. and if continuously changing tabs, UI thread dropped around 10-20 and app stuck. 

The UI thread dropped when changing tab
### Expected behaviour
when tab change does not effect on UI thread, like previous version, work perfect

### Your Environment
React-native: 0.63.4
react-native-tab-view: 3.0.0
react-native-pager-view: 5.1.2
Node: 14.15.4

**Comment by satya164** [comment]
Are you actually noticing any issues visually?
