### ISSUE TITLE
compatibility issue, children are not being rendered!

### ISSUE THREAD

**Issue by ahmedrowaihi** [satya164/react-native-tab-view#1163]
I guess this problem happens because of the latest react-native update and the issue is coming react-native

I noticed this message while compiling!

> Task :react-native-pager-view:compileDebugKotlin
w: C:\<projectFolder>\node_modules\react-native-pager-view\android\src\main\java\com\reactnativepagerview\PagerViewViewManager.kt: (74, 9): Condition 'child == null' is always 'false'
w: C:\<projectFolder>\node_modules\react-native-pager-view\android\src\main\java\com\reactnativepagerview\PagerViewViewManager.kt: (152, 11): 'receiveCommand(T, Int, ReadableArray?): Unit' is deprecated. Deprecated in Java
w: C:\<projectFolder>\node_modules\node_modules\react-native-pager-view\android\src\main\java\com\reactnativepagerview\PagerViewViewManager.kt: (158, 24): Unnecessary non-null assertion (!!) on a non-null receiver of type EventDispatcher
w: C:\<projectFolder>\node_modules\react-native-pager-view\android\src\main\java\com\reactnativepagerview\PagerViewViewManager.kt: (163, 24): Unnecessary non-null assertion (!!) on a non-null receiver of type EventDispatcher

HERE IS A SCREENSHOTTT

https://prnt.sc/11194na

| software                     | version
    yarn
    android
    "react-native": "0.64.0",
    "react-native-tab-view": "^3.0.0",
    "react-native-pager-view": "^5.1.2",

**Comment by fi-hunter** [comment]
I am also having the same issue and have the same package versions as OP has. Did anyone find a work around for this?

**Comment by chaaya** [comment]
Also facing the same issue when upgrading from v2.1.6 to v3.0.1. Tabs was rendered fine in 2.1.6, but not rendering in 3.0.1. I can see that my component mounts using the useLayoutEffect hook but nothing is rendered on the screen. Must be some kind of bug with the tab component not getting a height or something?

**Comment by Harkindey** [comment]
I just experienced this just now, and anytime i add a ScrollView to the screen, my tab rendering disappears.

**Comment by chrisvasey** [comment]
> installing an old version like 2.14.4, got it working again.

Can confirm, this also resolved the issue for me
