### ISSUE TITLE
Setting tab index other than 0.

### ISSUE THREAD

**Issue by Saad-Bashar** [satya164/react-native-tab-view#1168]
I want to set the default active tab index to 1. I am using setIndex to change the index value to 1 from 0. But it does not change the tab whereas a hard refresh on the simulator works.  Not sure where I am going wrong with this.  All the components are declared outside of my component. Any suggestion on this, please? Maybe I am doing something very silly. 

My tabview version is ---- "react-native-tab-view": "^2.15.2",

1. I am trying to change the index inside a useEffect depending on my data.
```
useEffect(() => {
      if(_.size(newReservations) === 0 && _.size(acceptedReservations) > 0) {
        console.log("SETINDEX") // this console log works as well.
        setIndex(1) // even after setting the index here to 1, the active tab remains at index 0
      }
  }, [reservation.list]);
```

**Here even the index is 1 when I console.log(index). But the tab is not moving.**

2. This is my tab view.
```
<TabView
        navigationState={{index, routes}}
        renderScene={renderScene}
        onIndexChange={(index) => setIndex(index)}
        initialLayout={initialLayout}
        renderTabBar={renderTabBar}    
 />
```

3. This is my renderScene func
```
 const renderScene = ({ route }) => {
    switch (route.key) {
      case 'new':
        return (
          <View style={[styles.scene]}>
            <NewTab type="new" list={newReservations} />
          </View>
        );
      case 'accepted':
        return (
          <View style={[styles.scene]}>
            <AcceptedTab type="accepted" list={acceptedReservations} />
          </View>
        );
      default:
        return null;
    }
  };
```
**Like in the image, the active indicator is at new whereas it should  be on accepted.**
![Screenshot 2021-04-08 at 3 01 03 PM](https://user-images.githubusercontent.com/13269141/113982369-415dd580-987b-11eb-9161-465af85dab35.png)

**Comment by khanhtn91** [comment]
Hi @Saad-Bashar ,
I have this same issue as well, I can't set the default active tab via props
I found a solution to fix it
Init default index value for the state, this value will set the default for the first render of the tab
```
const [state, setState] = useState({
  index: props.indexSelectTab || 0,
  routes: props.routes,
})

const onPressTab = (i) => {
  setState({
    ...state,
    index: i,
  })
}

<TabView
  navigationState={{index: state.index, routes: state.routes}}
  renderScene={_renderScene}
  renderTabBar={_renderTabBar}
  onIndexChange={_handleIndexChange}
  onSwipeEnd={() => onPressTab(state.index)}
/>
```
hope this helps.

**Comment by Saad-Bashar** [comment]
Hey @khanhtn91 , thanks for your comment! In my use case, it was a bit different. Not I am setting the index and while setting it I am not showing the tab bar. something like this 

```
useEffect(() => {
    const tab = route.params?.tab ?? 'active';
    if(tab === 'upcoming') {
      setIndex(1)
    } else {
      setDefaultTab()
    }
  }, [navigation]);

const setDefaultTab = () => {
    if(_.size(activeBookings) === 0 && _.size(upcomingBookings) > 0) {
      setIndex(1)
    } else {
      setIndex(0)
    }
  }
```

Am I making it way too complicated?

**Comment by sabonis** [comment]
![Screen Shot 2022-08-26 at 3 38 11 PM](https://user-images.githubusercontent.com/1359697/186849087-ee01446e-3987-411d-866c-158a2e0d1f08.png)
from https://beta.reactjs.org/learn/you-might-not-need-an-effect

useEffect is unneeded, just calling setIndex() in the function is better.

**Comment by cxt19951016** [comment]
same issue,could you please tell me how to solve it?
