### ISSUE TITLE
Custom tab bar with reanimated 2

### ISSUE THREAD

**Issue by yanush** [satya164/react-native-tab-view#1170]
Is it possible to use custom tab bar with reanimated 2 api?
If so, how should one animate the 'position'?

react-native: 0.64.0
react-native-tab-view: 3.0.1
react-native-pager-view: 5.1.3

**Comment by yanush** [comment]
react-native: 0.64.0
react-native-tab-view: 3.0.1
react-native-pager-view: 5.1.3

**Comment by satya164** [comment]
No, we don't use Reanimated in the library. You can open an issue in Reanimated repo for interop with Animated Value.
