### ISSUE TITLE
[v3] Can't prevent overdrag on iOS

### ISSUE THREAD

**Issue by plus-** [satya164/react-native-tab-view#1172]
### Current behaviour

I can't prevent the horizontal bounce effect on IOS. 

### Expected behaviour

I can set the overdrag property to false to prevent bounce on iOS

### What have you tried

I've tried setting  react-native-pager-view [overdrag](https://github.com/callstack/react-native-pager-view/blame/6ba8356cba68e1a7350c8f2ae7a7b24317c30ce6/src/types.ts#L121) to false, but it's not doing anything. I believe it's because the version used by this package is 4.2.4, and the property is only available in 5.x

| software                     | version
| ---------------------------- | -------
| ios or android               |
| expo                         |
| react-native                 | 0.63.4
| react-native-tab-view        | 3.0.1
| react-native-pager-view      | 5.1.3
| node                         |
| npm or yarn                  |

**Comment by tanjiaweiGitHub** [comment]
Please add the overdrag attribute to control the problem of ios excessive drag

**Comment by satya164** [comment]
>  believe it's because the version used by this package is 4.2.4, and the property is only available in 5.x
`react-native-pager-view` is a peer dependency that you install in your project. the library doesn't use any specific version, it uses whatever version you install

**Comment by okwasniewski** [comment]
Hey, `overdrag` prop in `react-native-pager-view` now defaults to false so it shouldn't be a problem, closing this.
