### ISSUE TITLE
 Crash when combined with react-native-picker/picker and problems in navigation in 3.0.0 and 3.0.1

### ISSUE THREAD

**Issue by java666p** [satya164/react-native-tab-view#1173]
Crash when combined with react-native-picker/picker and problems in navigation.

### Current behaviour

Hey Satyajit, thank for your amazing work in react-native-tab-view. I hope you keep up the amazing work. I noticed a strange issues in the latest update from 2.16.0 to 3.0.0 after you started using react-native-pager-viewer. We use react-native 0.64 on android. When we use react-native-tab-view 3.0.0 with react-native-picker/picker we noticed the picker crashed. And then when we downgrade back to 2.16.0 it was stable again. Also we noticed in react-native-tab-view 3.0.0 had problem navigating to a particular tab index from another page, it kept resetting back to the first index 0 which is the first tab when the page loads. We again resolved it by switching back to 2.16.0. Am just writing this to let you know because we are not sure if it is from your migration to react-native-pager-view causing this problems or a bug.

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |android
| react-native                 |0.64
| react-native-tab-view        |3.0.0
| react-native-pager-view      |5.1.2
| npm or yarn                  |npm

**Comment by thanhdatpd** [comment]
bump
