### ISSUE TITLE
Can't change labelStyle color in <TabBar>

### ISSUE THREAD

**Issue by enigmablue** [satya164/react-native-tab-view#1175]
Unfortunately, something as simple as the code below, changing the labelStyle color dosen't work. 

Anyone know what is the right way? i checked all the examples but dont see an example.

I checked the TabBar.tsx and it looks like just a StyleProp<TextStyle>;

```
  <TabBar
    {...props}
    indicatorStyle={{ backgroundColor: '#29ad60' }}
    labelStyle={{ color: 'black',  fontSize: 20}}
    style={{ backgroundColor: '#3f51b5', color:"green" }}
  />
```
  "react-native-tab-view": "^3.0.1",
  "react-native": "0.63.3",
  "react-native-pager-view": "^5.1.2",

**Comment by kutsan** [comment]
https://github.com/satya164/react-native-tab-view/issues/583#issuecomment-414625899
