### ISSUE TITLE
TabView issue inside ScrollView

### ISSUE THREAD

**Issue by ahtishamali09** [satya164/react-native-tab-view#1180]
Hello EveryOne i hope you guys doing well i facing Scrolling issue flatlist data is not showing

 <ScrollView contentContainerStyle={{flexGrow: 1}}>
        <View style={styles.MainContainer}>
          <View>
            <View style={{marginHorizontal: 28, marginTop: 20}}>
              <Text style={{color: 'white'}}>
                We at medtigo believe in a culture of transparency and
                reliability. We are more than just a recruiting firm. We are
                your personal agent.
              </Text>
            </View>
            <FlatList
              horizontal={true}
              data={SwippableData}
              showsHorizontalScrollIndicator={false}
              renderItem={({item, index}) => (
                <View>
                  <SwippableTile item={item} />
                </View>
              )}
            />
          </View>
          <View style={styles.seprator} />
          <TabView
            navigationState={{index, routes}}
            renderScene={SceneMap({
              first: FirstRoute,
            })}
            onIndexChange={setIndex}
            renderTabBar={props => (
              <TabBar
                {...props}
                indicatorStyle={styles.indicatorStyle}
                style={styles.tabBar}
                renderLabel={route => (
                  <Text style={styles.routerTitle}>{route.route.title}</Text>
                )}
                inactiveColor="#c2c3c8"
              />
            )}
          />
        </View>
      </ScrollView>

`First Route`
const FirstRoute = () => (
    <View
      style={{
        flex: 1,
      }}>
      <View style={styles.container}>
        <FlatList
          scrollEnabled={false}
          data={jobData}
          keyExtractor={(item, index) => index.toString()}
          renderItem={({item}) => (
            <View>
              <JobsData {...props} item={item} navigation={navigation} />
            </View>
          )}
        />
        {jobData && jobData.length > 0 && (
          <View>
            <StaffingCard onPress={() => setShowModal(true)} />
          </View>
        )}
      </View>
    </View>
  );

**Comment by MahmonirB** [comment]
I have same problem,

I resolved it by down grade version of this package to `"react-native-tab-view": "^2.16.0",`

**Comment by shensven** [comment]
same issue in 3.0.1

**Comment by ezbank** [comment]
I have same problem,

**Comment by etonnelier** [comment]
@MahmonirB worked, thanks you!

**Comment by rajvir13** [comment]
@MahmonirB Thanks, worked for me too.

**Comment by taxidermic** [comment]
Measuring and setting height manually solved it for me: https://github.com/callstack/react-native-pager-view/issues/386

**Comment by abhiburk** [comment]
@MahmonirB Thanks! I do not know how it worked just by downgrading the package. Well It worked though

**Comment by gauravroyzz** [comment]
> * With 3.1.1, the TabView content (whatever it is) is not displayed if the TabView has a ScrollView parent.

is this resolved?

**Comment by CaiqueTuioshi** [comment]
> I have same problem,
> 
> I resolved it by down grade version of this package to `"react-native-tab-view": "^2.16.0",`

This solved my problem!!

But now i'm having problem with my unit tests.
I get `Invariant Violation: Unable to locate attached view in the native tree` and `The above error occurred in the <AnimatedComponent(View)> component:`

Anyone else had this problem?
