### ISSUE TITLE
Tab Scene with Flatlist not rendered until scrolling when switched to another tab

### ISSUE THREAD

**Issue by iKoru** [satya164/react-native-tab-view#1190]
### Current behaviour
The flattest inside of a scene is not rendered until scroll when switched to another tab

similar to issue #991 but for v3.0.1

### Expected behaviour
Any contents of a scene is rendered immediately switched to containing tab

### Code sample

For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

### Screenshots (if applicable)

![bug2](https://user-images.githubusercontent.com/7664952/121038701-74750480-c7eb-11eb-84da-0e812a635d61.gif)

### What have you tried

set LazyEndabled as false
programmatically manipulate scroll position whenever tab changes

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | iOS 
| expo                         | 41.0.0
| react-native                 |0.63.4
| react-native-tab-view        |3.0.1
| react-native-pager-view      |5.0.12
| node                         |12
| npm or yarn                  |yarn

**Comment by eugen2991** [comment]
did you fix it?

**Comment by iKoru** [comment]
@eugen2991 nope. I've just downgraded this lib to 2.x.x.
