### ISSUE TITLE
 render same scene view

### ISSUE THREAD

**Issue by supermaverickws** [satya164/react-native-tab-view#1195]
if i don`t start lazy model, some times  int nested tabview , some tabview will render same scene view! 
react-native: 0.64.2
react-native-tab-view: 3.0.1
react-native-pager-view: 5.1.7

**Comment by supermaverickws** [comment]
it happend when I used custom spilt bundle model. so that  cant debug.
but use  lazy or  normal debug . it's nice

**Comment by SanjanaTailor** [comment]
re-render for scenViewObject inside not happening
