### ISSUE TITLE
iOS: initial tab bar scene not loaded automatically - 3.0.1

### ISSUE THREAD

**Issue by palania-fl** [satya164/react-native-tab-view#1196]
### Current behavior
We have configured a number of tabs with scenes map. The initial tab is not getting load by default. I have to click the indicated tab to get to visible the screen. It, no a problem in 2.16.0
This is happening in iOS alone

### Expected behavior
The initial state scene should load default in ios

### Code sample

<TabView
                    lazy={true}
                    tabBarPosition={'bottom'}
                    navigationState={state}
                    renderScene={props.renderScene}
                    onIndexChange={setIndex}
                    swipeEnabled={false}
                    initialLayout={{ height: 0, width: layout.width }}
                    renderTabBar={defaultRenderTabBar}
                />
Due to other confidentiality, I am not able to share the full code

### Screenshots (if applicable)
![Tab issue](https://user-images.githubusercontent.com/84391419/122581976-40b09f00-d075-11eb-98f4-85cbecc80f3f.png)

### What have you tried

I tried to load the list card carousel in each scene

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios              |.   ios 11.4
| react-native                 | 4.14.0
| react-native-tab-view        | 3.0.1
| react-native-pager-view      |  ^5.2.1
| node                         | v14.17.0
| npm or yarn                  | 6.14.13

**Comment by pnogier** [comment]
Same issue here, my component is loaded, but not displayed.
Did someone find a solution ?

**Comment by DonovanCharpin** [comment]
I have the same issue with he same version. Did you find a fix?

**Comment by pnogier** [comment]
Hi there, I found a solution...
Actually I am dynamically creating my routes,
When I was experiencing this issue i was declaring my state variable like this : 
```javascript
const [routes, setRoutes] = useState([]);
```
And using the `setRoutes` method in a useEffect hook, which was dynamically getting my routes.
I cant explain why my tab bar was correctly rendering and the code inside my components was run, but I just had to initially not set my routes instead of setting it to an empty array, then add a check to render the TabView: 

```javascript
const [routes, setRoutes] = useState();

return (
  <>
    {routes && 
      <TabView
        {...props}
      />
    }
  </>
)
```

Hope it can help some of you,

Cheers

**Comment by palania-fl** [comment]
@pnogier, Thanks for sharing.  Not working for me

**Comment by enormousrodent** [comment]
I have same issue...Any update

**Comment by rafaelmdarocha** [comment]
Thanks @pnogier, this was the last thing I needed to solve to finish my application.
Just remembering that useState must be initialized without an empty array, in case someone hasn't got it yet.
`const [routes, setRoutes] = useState();`

**Comment by alejandrosaldarriagaGL** [comment]
I have the same issue in android.
My app is also using components approach and cannot implement the solution suggested by @pnogier. I try validating only similar to this but didn't work.

```
routes && 
      <TabView
        {...props}
      />
```

If I use version ^2.10.0 doesn't happen.
Happens in version ^3.0.1
