### ISSUE TITLE
TabView inside a View does not shows up

### ISSUE THREAD

**Issue by fsitios** [satya164/react-native-tab-view#1205]
### Current behaviour

If I insert the TabView inside a View, the TabView doesn't appear at all. But if I remove it from View, it appears.

### Expected behaviour

Being able to insert a TabView within a View, to display additional components on the same screen.

### Code sample

```
  return (
    <View>
       <SomeOtherComponents />
      <TabView
                navigationState={{ index, routes }}
                renderScene={renderScene}
                onIndexChange={setIndex}
                initialLayout={layout}
                style={styles.tabContainer}
      />
    </View>
  );
```

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |  IOS 14.6
| expo                         |   4.7.3
| react-native                 |  https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz
| react-native-tab-view        | 3.0.1
| react-native-pager-view      | 5.0.12
| node                         |  14.15.4
| npm or yarn                  | 6.14.10

**Comment by fsitios** [comment]
Same problem using:

- expo 42.0.0
- react-native-pager-view 5.2.1 is not compatible with expo 42.0.0, it must be 5.0.12
- react-native: 0,63  (is what is informed on the [expo 42 upgrade blog ](https://blog.expo.io/expo-sdk-42-579aee2348b6))

**Comment by satya164** [comment]
Add `flex: 1` to your `View`
