### ISSUE TITLE
value getValue, App is crashing when renders TabView

### ISSUE THREAD

**Issue by Aqhamza** [satya164/react-native-tab-view#1206]
### Current behaviour

[Android] The app is crashing when the screen renders the TabView and there is no information on this crash. This is only crashing on Android working fine on iOS.

### Expected behaviour

The expected behavior is to render the TabView content

```
renderTabBar = (
    //@ts-ignore
    props: SceneRendererProps & {navigationState: State}
  ) => (
    <View style={styles.tab_bar}>
          <ScrollView showsHorizontalScrollIndicator={false} horizontal={true}>
            {props.navigationState.routes.map((route, index) => {
              return (
                <TouchableWithoutFeedback
                  key={route.id}
                  onPress={() => this.handleIndexChange(index)}
                  style={[
                    styles.tab,
                    index === props.navigationState.selected_index && styles.selected_tab,
                    {
                      marginRight: props.navigationState.routes.length - 1 === index ? 12 : 0,
                    },
                  ]}>
                  <Text
                    category={'h6'}
                    style={global.regular_bold_family}
                    status={index === props.navigationState.selected_index && 'control'}>
                    {route.title}
                  </Text>
                </TouchableWithoutFeedback>
              );
            })}
          </ScrollView>
        </View>
  );
  renderScene = ({route}) => {
    const {
      tab_associated_data,
      selected_tab,
    } = this.state;
    const { parent_data } = this.props;
    switch (route.type && selected_tab) {
      case 'content': {
        return (
          <TopicContentContainer
            {...this.props}
            topic_associated_data={tab_associated_data}
            parent_data={parent_data}
            tab_data={selected_tab}
          />
      );
      }
      default:
        return null;
    }
  };

  render() {
    const { fetching_tab_data, fetching_tab_data_error, tab_associated_data } = this.state;
    return (
      <Layout
        style={[
          global.page_container_with_aligned_flex_start,
          {paddingTop: 0},
        ]}>
          {
            !fetching_tab_data && !fetching_tab_data_error &&
              tab_associated_data ? (
                <TabView
                  navigationState={this.state}
                  renderScene={this.renderScene}
                  renderTabBar={this.renderTabBar}
                  initialLayout={initialLayout}
                  onIndexChange={this.handleIndexChange}
                />
              ) : fetching_tab_data ? (
                <LoadingIndicator style={{marginTop: 16}} size="large" />
              ) : (
                fetching_tab_data_error && (
                  <TapToReload onPress={() => this.fetchTabContent()} />
                )
              )
          }
      </Layout>
    );
  }
```
![Screenshot 2021-07-17 at 1 58 43 AM](https://user-images.githubusercontent.com/22516129/126007857-7b6b9075-0f85-4bfc-9727-6d601759aa8d.png)

### What have you tried

After installing the react-native-tab-view and react-native-pager-view on given versions app successfully builds but When I open the screen rendering with TaBView it crash with an error as shown in Screenshot.

Note: If I install the latest version <^5.2.1> of react-native-pager-view app doesn't build on Android and gives the Kotlin error.
Execution failed for task ':react-native-pager-view:compileDebugKotlin'.
A screenshot of this error is also given.
Anyone here can help to build the project with the latest version or fix the error on the previous version.
Thanks.
![Screenshot 2021-07-17 at 2 06 09 AM](https://user-images.githubusercontent.com/22516129/126008516-9587f17c-538b-46d7-88d8-64b68466997d.png)

| software                     | version
| ---------------------------- | -------
| ios or android               | Android
| expo                         | 
| react-native                 | 0.62.2
| react-native-tab-view        | ^3.0.1
| react-native-pager-view      | 5.0.12
| node                         | v14.17.1
| npm or yarn                  | 6.14.13

**Comment by jensonstack** [comment]
+1 Same issue,  iOS working fine, android crashing. @Aqhamza did you resolve this issue?

**Comment by ganeshhoramata** [comment]
+1 Same issue, android crashing. @Aqhamza did you resolve this issue?
