### ISSUE TITLE
React Native TabView + FlatList: scrollbar automatically scrolls to top when using onEndReached

### ISSUE THREAD

**Issue by tranthanhtung04101995** [satya164/react-native-tab-view#1207]
### Current behaviour
Incorrect behavior of the FlatList's "onEndReached" element while using the FlatList inside of the TabView
Scrollbar automatically scrolls to top when using onEndReached

### Expected behaviour
Common behavior of the "onEndReached" feature: 
When scrolling to the top of the page, loads more data and the scrollbar doesn't jump to the top

### Code sample
Using TabView
```
<TabView
      renderTabBar={renderTabBar}
      navigationState={{ index, routes }}
      renderScene={renderScene}
      onIndexChange={setIndex}
      initialLayout={{ width: layout.width }}
  />
```
renderScene 
```
const renderScene = SceneMap({
        first: () => <WaitConfirm data={listOrder} handleItemClick={handleItemClick} handleLoadMore={handleLoadMore}/>,
        second: () =>  <SecondRoute data={listOrder1} handleItemClick={handleItemClick}/>,
        third:  () =>  <ThirdRoute data={listOrder2}  handleItemClick={handleItemClick}/>,
        four:  () =>  <FourRoute data={listOrder3}  handleItemClick={handleItemClick}/>,
    });
```
Flatlist
```
const WaitConfirm = (props) => {
    return (
    <View style={{ flex: 1, height, width,backgroundColor: '#e1ecf4'}} > 
        <FlatList 
            data={props.data}
            showsHorizontalScrollIndicator = {false}
            keyExtractor = {item => item.id.toString()}
            showsVerticalScrollIndicator={false}
            showsHorizontalScrollIndicator={false}
            contentContainerStyle={{}}
            style={{flex: 1,width}}
            onEndReached={() => props.handleLoadMore(0)}
            onEndReachedThreshold={0.01}
            renderItem = {({item}) => {
                return <View>
                ....
                </View>
           }}
        /> 
</View>

)};

export default WaitConfirm;
```

### Screenshots (if applicable)
[https://raw.githubusercontent.com/tranthanhtung04101995/bot_zalo/master/error.gif](url)

### Your Environment

| software                     | version
| ---------------------------- | -------
| react-native                 | "0.64.2"
| react-native-tab-view        | "^3.0.0"
| react-native-pager-view      | ^5.1.2
| node                         |  v12.16.3
| npm                          |  6.14.4

**Comment by tranthanhtung04101995** [comment]
The issue still exists after upgrading to the latest versions.

**Comment by satya164** [comment]
You're doing what docs explicitly say not to do https://github.com/satya164/react-native-tab-view#renderscene-required

**Comment by enrickdaltro** [comment]
@tranthanhtung04101995 I'm having the same issue. Did you manage to get it working properly?
