### ISSUE TITLE
iOS: indicator position animates incorrectly when navigating over multiple pages

### ISSUE THREAD

**Issue by captain-refactor** [satya164/react-native-tab-view#1211]
### Current behaviour
On iOS:
Page scroll indicator animates to next navigation button and then jumps to correct navigated button. 
The issue is position Animated.Value, it changes like this:
```json
{"value":0}
{"value":0.007788162212818861}
{"value":0.0303738322108984}
{"value":0.06697819381952286}
{"value":0.11682242900133133}
{"value":0.17834891378879547}
{"value":0.25}
{"value":0.32866042852401733}
{"value":0.413551390171051}
{"value":0.5}
{"value":0.5872274041175842}
{"value":0.6713395714759827}
{"value":0.75}
{"value":0.8216511011123657}
{"value":0.8831775784492493}
{"value":0.9330217838287354}
{"value":0.9696261882781982}
{"value":0.9922118186950684}
{"value":1}
{"value":3}
```
The Android behavior is all right.

### Expected behaviour

Page scroll indicator should animate right to correct navigation button. Position value should interpolate the whole way from start index to destination index (same as it works on android)

### Code sample

I've created a repo https://github.com/captain-refactor/tab-view-position-bug

### Screenshots (if applicable)

![indicator_position](https://user-images.githubusercontent.com/42211280/126630641-106b8d1e-fdcb-44c2-921e-9afad14f1932.gif)

### What have you tried

I were debugging and found out that onPageScroll behaves differently on android and ios. https://github.com/satya164/react-native-tab-view/blob/dad1e49f6cefcd7ba5eb062775f9e9fb06b875ad/src/Pager.native.tsx#L131

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | ios simulator 14.5
| expo                         |  42.0.3
| react-native                 | 0.63.2
| react-native-tab-view        |  3.0.1
| react-native-pager-view      | 5.3.1
| node                         |  v14.15.4
| npm or yarn                  | yarn 1.22.10

**Comment by captain-refactor** [comment]
I upgraded react-native version and the issue still persist

**Comment by troZee** [comment]
Could you test my changes ? https://github.com/callstack/react-native-pager-view/pull/435
