### ISSUE TITLE
On initial load I have set index as 1 not 0. It will automatically show 0 index scene.

### ISSUE THREAD

**Issue by Sivaram-Harivara** [satya164/react-native-tab-view#1246]
### Current behavior

![Screenshot_2021-08-18-12-16-45-06_f73b71075b1de7323614b647fe394240](https://user-images.githubusercontent.com/81281824/129851442-bb8bcc8d-324a-4f8c-a574-5f12ba801d4c.jpg)

### Expected behavior

![Screenshot_2021-08-18-12-16-48-19_f73b71075b1de7323614b647fe394240](https://user-images.githubusercontent.com/81281824/129851496-ec088574-0a6f-43a4-b935-3ea2767d020b.jpg)

### Reproduction

---

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by raquelmsmith** [comment]
Did you ever get around this? I'm having the same issue.

**Comment by amauridiastc** [comment]
@raquelmsmith  i solved the problem by updating react-native-pager-view and react-native-tab-view

versions that solved it for me:

```js
"react-native-tab-view": "3.1.1",
"react-native-pager-view": "5.4.15",
```

**Comment by fxamauri** [comment]
@raquelmsmith  i solved the problem by updating react-native-pager-view and react-native-tab-view

versions that solved it for me:

```js
"react-native-tab-view": "3.1.1",
"react-native-pager-view": "5.4.15",
```
