### ISSUE TITLE
Quick Swipe Gesture Causes Race Condition on onIndexChange (Android)

### ISSUE THREAD

**Issue by NemyaNation** [satya164/react-native-tab-view#1250]
## EPILEPSY WARNING
https://user-images.githubusercontent.com/17049683/130364091-715c0cea-63d7-4005-8385-fac167bfe735.mp4

First 2-3 seconds, I show a regular swipe-right followed by a swipe-left which works fine (using the TabBar example)

Then the following 2-3 seconds I swipe right as usual, but quickly swipe left before the animation has finished.

This causes the infinite loop shown in the video at the end, this will continue until I restart the screen.

### Expected behavior

Just go back to the first screen as usual.

### Reproduction

Will provide later

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  | "^3.1.1"
| react-native-pager-view                | "^5.4.0"
| react-native                           | ~0.63.3
| expo                                   | ^38.0.0 (ejected)
| node                                   | v14.2.0
| npm or yarn                            | yarn

**Comment by MichaelBorde** [comment]
Issue seems to appear with `react-native-pager-view` `5.3.3`. It's ok in `5.3.2` (and previous versions).

**Comment by cjhines** [comment]
Can confirm this happens a lot

**Comment by KashaTeplaya** [comment]
Downgrade to react-native-pager-view v4 results in InitialRouteName not working for me

**Comment by cjhines** [comment]
Anyone managed to determine where the race condition happens? Is this an issue of this library or of `react-native-tab-view`?

I ask because I do not see anything in their issues.

**Comment by bang88** [comment]
Any solutions?

**Comment by krik** [comment]
I tracked it down to the initialPage repeatedly being updated, anyone daring to confirm the fix? https://github.com/hybridheroes/react-native-tab-view/commit/877444021a78742a5f848cb2b37e7cf59deda21d

**Comment by KashaTeplaya** [comment]
> I tracked it down to the initialPage repeatedly being updated, anyone daring to confirm the fix? [hybridheroes@8774440](https://github.com/hybridheroes/react-native-tab-view/commit/877444021a78742a5f848cb2b37e7cf59deda21d)
Thank you a lot, its work for me!!!

**Comment by mrshahzeb7** [comment]
> > I tracked it down to the initialPage repeatedly being updated, anyone daring to confirm the fix? [hybridheroes@8774440](https://github.com/hybridheroes/react-native-tab-view/commit/877444021a78742a5f848cb2b37e7cf59deda21d)
> 
> Thank you a lot, its working for me!!! In react-native-top-tab was same issue, your fix resolving it, i have put link of your solution in react-native-top-tab [react-navigation/react-navigation#9966 (comment)](https://github.com/react-navigation/react-navigation/issues/9966#issuecomment-929198999)

please tell me how can I solve this for react navigation material top tab ?

**Comment by troZee** [comment]
Hello 👋 
I can't transfer an issue to pager view repo, so I `cloned` this issue to pager view. I will take a look on it.

**Comment by troZee** [comment]
The PR has been created. Can anyone test my changes ?

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/releases/tag/v5.4.5
