### ISSUE TITLE
Scroll after switching tabs does not register properly

### ISSUE THREAD

**Issue by tdekoning** [satya164/react-native-tab-view#1255]
### Current behavior

This is an issue that, as far as i can see, is only occurring on Android.

In the situation where you have 2 (or more) tabs that have content which is scrollable, and the tab-view has `swipeEnabled={true}`. When the user switches from 1 tab to the other (see video), the first scroll interaction is not picked up by the scrollview inside the tab, but is captured by react-native-tab-view.

The strange thing is, that in the expo snack that i've linked, the behavior isn't present. However, when creating a react-native project from scratch (using react-native cli), and using the following code, the issue does happen.

Package.json:
```package.json
"dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.0",
    "react-native-pager-view": "^5.4.1",
    "react-native-tab-view": "^3.1.1"
  }
```

App.js:
```App.js
import * as React from 'react';
import { ScrollView, Text, StyleSheet } from 'react-native';
import { TabView, SceneMap } from 'react-native-tab-view';

const FirstRoute = () => (
  <ScrollView style={{ flex: 1, backgroundColor: '#ff4081' }}>
    <Text style={styles.text}>This is text</Text>
    <Text style={styles.text}>This is text</Text>
    <Text style={styles.text}>This is text</Text>
    <Text style={styles.text}>This is text</Text>
    <Text style={styles.text}>This is text</Text>
    <Text style={styles.text}>This is text</Text>
    <Text style={styles.text}>This is text</Text>
    <Text style={styles.text}>This is text</Text>
    <Text style={styles.text}>This is text</Text>
    <Text style={styles.text}>This is text</Text>
    <Text style={styles.text}>This is text</Text>
  </ScrollView>
);

const SecondRoute = () => (
  <ScrollView style={{ flex: 1, backgroundColor: '#673ab7' }}>
    <Text style={styles.text}>This is text</Text>
    <Text style={styles.text}>This is text</Text>
    <Text style={styles.text}>This is text</Text>
    <Text style={styles.text}>This is text</Text>
    <Text style={styles.text}>This is text</Text>
    <Text style={styles.text}>This is text</Text>
    <Text style={styles.text}>This is text</Text>
    <Text style={styles.text}>This is text</Text>
    <Text style={styles.text}>This is text</Text>
    <Text style={styles.text}>This is text</Text>
    <Text style={styles.text}>This is text</Text>
  </ScrollView>
);

const renderScene = SceneMap({
  first: FirstRoute,
  second: SecondRoute,
});

export default function TabViewExample() {

  const [index, setIndex] = React.useState(0);
  const [routes] = React.useState([
    { key: 'first', title: 'First' },
    { key: 'second', title: 'Second' },
  ]);

  return (
    <TabView
      style={{marginTop: 32}}
      navigationState={{ index, routes }}
      renderScene={renderScene}
      onIndexChange={setIndex}
      swipeEnabled={true}
    />
  );
}

const styles = StyleSheet.create({
  text: {fontSize: 50, marginBottom: 64}
})

```

### Expected behavior

I expect that a vertical scroll (and keeping in mind that users don't scroll 100% vertical) is picked up by the component inside of the tab (such as the scrollview in my example), so that the user can access all the content that is available. 

### Reproduction

https://snack.expo.dev/@ted-q42/tabbar-scrollview

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  | 3.1.1
| react-native-pager-view                | 5.4.1
| react-native                           | 0.65.1
| expo                                   | (not using expo)
| node                                   | v14.16.0
| npm or yarn                            | 6.14.11

**Comment by tdekoning** [comment]
Expo isn't used in my project

**Comment by Guuz** [comment]
I tested this in my team's app as wel. We are still using v2 of react-native-tab-view. But as soon as we upgrade to v3, that uses the pager-view package, this happens. The scroll/swipe down is registered as a vertical swipe. This is a major UX-problem and prevents us from upgrading.

**Comment by nericode** [comment]
I have same issue :(

**Comment by arturovv** [comment]
Same issue here. It prevents us from upgrading as well. Easily reproducible on device, not always on simulator. Android only issue.

```
"dependencies": {
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/material-top-tabs": "^6.0.2",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    "react": "17.0.2",
    "react-native": "0.65.1",
    "react-native-pager-view": "^5.4.1",
    "react-native-safe-area-context": "^3.3.0",
    "react-native-screens": "^3.6.0",
    "react-native-tab-view": "^3.1.1",
  }
```

**Comment by christianstefaniw** [comment]
same issue

**Comment by thorewi** [comment]
same issue

**Comment by mikesoko** [comment]
I have the same issue on Android

**Comment by imavipatel** [comment]
same issue @satya164 please resolve this sir
