### ISSUE TITLE
Switching tabs requires more than one press until transition animation is over.

### ISSUE THREAD

**Issue by chrissehic** [satya164/react-native-tab-view#1257]
### Current behavior

I have tried using ```scrollEnabled: true``` or equivalently ```tabBarScrollEnabled: true``` on a ```createMaterialTopTabNavigator``` as well as directly in a ```react-native-tab-view```.
In both cases, when tabBarScrollEnabled is true the top tabs don't switch on first press/tap in both modules, they only switch when double-pressed. They seem to be waiting for the indicator/centering animation to end before the press allows to switch to another tab. This issue only arises on Android via Expo.

### Expected behavior

I am expecting the tabs to switch when pressed once, even with ```tabBarScrollEnabled``` set to true.

### Reproduction

https://github.com/roccosiffredi/react-native-tab-view/blob/main/example/src/ScrollableTabBarExample.tsx

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  | ^3.1.1 |
| react-native-pager-view                | 5.0.12 |
| react-native                           | 0.63.4 |
| expo                                   | ^42.0.0 |
| node                                   | v14.15.3 |
| yarn                            | 1.22.10 |

**Comment by roccosiffredi** [comment]
repo is updated: https://github.com/roccosiffredi/react-native-tab-view/blob/main/example/src/ScrollableTabBarExample.tsx

**Comment by roccosiffredi** [comment]
Issue still exists after upgrading the indicated packages to their latest versions.

**Comment by IsmetGlumcevic** [comment]
same issue

**Comment by chrissehic** [comment]
issue still present
