### ISSUE TITLE
(Warning) Sending `onAnimatedValueUpdate` with no listeners registered.

### ISSUE THREAD

**Issue by Choyeongdeok** [satya164/react-native-tab-view#1258]
### Current behavior

When I swipe fast between tabs,
I get a warning 'Sending onAnimatedValueUpdate with no listeners registered.' only in ios.

https://user-images.githubusercontent.com/54658590/132441362-71bea3f6-d984-403b-90f5-5949c150a778.mp4

### Expected behavior

It's not an error, but I want to resolve it. Is there any answer?
If there is no anwser, I'll use log box to hide it.

### Reproduction

no repro

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

"react-native-pager-view": "5.4.0",
"react-native-tab-view": "3.1.1",
"react-native": "0.64.1",

**Comment by lclrobert2020** [comment]
this problem still exist

**Comment by akshilshah** [comment]
Workaround for the issue is to ignore warnings

Import it in ```App.js``` file

Code:
```
import { LogBox } from 'react-native';
LogBox.ignoreLogs(['Sending']);
```

**Comment by Hirbod** [comment]
Ignoring Warnings is not always the right solution

**Comment by yuhr** [comment]
In any sense ignoring warnings is not a solution nor even a workaround. It means an abandonment of your software's maintenance.

**Comment by akshilshah** [comment]
@yuhr I totally agree with you in fact I am very actively looking for an option. Could you please share if you have fix the code because I am running this on production and I either need a fix or workaround.

**Comment by mAdutskevich** [comment]
same problem

**Comment by Mohamed-Raid** [comment]
any updates ?

**Comment by JungHsuan** [comment]
same here

**Comment by Oussama-Berrazaga** [comment]
same issue happens when I swipe from left to right on the first tab and when swiping right to left on the last tab

**Comment by KaluJo** [comment]
> same issue happens when I swipe from left to right on the first tab and when swiping right to left on the last tab

I'm having this exact problem. Has anyone found any clues to solving this?

**Comment by patrikalbertsson** [comment]
Same here

**Comment by gustavomanolo** [comment]
Same problem

**Comment by sanduluca** [comment]
Same problem.
No idea why on IOS there is no listeners registered for `onAnimatedValueUpdate`

**Comment by hadyca** [comment]
same problem..

**Comment by Jerryhuangjp** [comment]
For reference, there is no more warning when I put "else" rather than " else if " with the rest condition(my scenario: icon route.name). It also works under the way of  "switch case..." .

**Comment by vinaciotm** [comment]
same problem

**Comment by maksim-romanov** [comment]
Same problem :(
