### ISSUE TITLE
Android crash Expo SDK42

### ISSUE THREAD

**Issue by daganchen** [satya164/react-native-tab-view#1265]
### Current behavior

On iOS works great, Android complete crash!

### Expected behavior

Expecting Android to work as iOS

### Reproduction

https://snack.expo.dev/@arboxapps/test-tab-view

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  "^3.1.1"
| react-native-pager-view                 "5.0.12"
| react-native                           "0.63.2"
| expo                                   "42.0.0"
| node                                   "12.13.1"
| npm or yarn                            yarn

**Comment by daganchen** [comment]
Issue still exists on latest versions, repo updated.
Major issue because Google play store supports target SDK 30 + and expo supports SDK 30 from version 41+

**Comment by iaminarush** [comment]
Weird, works on my android phone. Maybe try downgrading react-native-pager-view package to 5.0.12 for expo 42 or upgrading your expo to 43 to support the newer versions of react-native-pager-view

**Comment by okwasniewski** [comment]
Closing this as stale
