### ISSUE TITLE
Unable to use swipe gesture to back on `TabView` scenes

### ISSUE THREAD

**Issue by mtflud** [satya164/react-native-tab-view#1286]
### Current behavior

React Navigation's navigation swipe gestures are not being recognized inside the `TabView` scene content, but they are being properly recognized inside the `TabBar` itself. 

Because of this, users are unable to use the "swipe back" gesture commonly used on iOS. 

Everything seems to be working normally on v2.16.0

### Expected behavior

Users should be able to swipe from left to right if on the first tab in order to navigate to the previous screen while on a `TabView` scene 

### Reproduction

https://github.com/mtflud/react-native-tab-view-swipe-back-repro

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  |  3.1.1
| react-native-pager-view                |  5.4.7
| react-native                           |  0.64.2
| expo                                   |  n/a
| node                                   |  14.17.3
| npm or yarn                            |  1.22.11
| react-navigation                            |  6

**Comment by JoniVR** [comment]
Can confirm that this is an issue, same here. Happens since React Navigation 6 upgrade.

**Comment by JoniVR** [comment]
<table>
<tr>
	<td> Version </td>
	<td> Package </td>
</tr>
<tr>
	<td>react-native-pager-view</td>
	<td>react-native-tab-view</td>
	<td>@react-navigation/material-top-tabs</td>
	<td>react-native</td>
</tr>
<tr>
	<td>5.4.8</td>
	<td>3.1.1</td>
	<td>6.0.6</td>
	<td>0.66.1</td>
</tr>
</table>

**Comment by JoniVR** [comment]
FYI, downgrading `react-native-tab-view` to `v2.16.0` seems to resolve the issue for now, for those who are running into the same issue...

**Comment by RajeshSFS** [comment]
Hi Everyone,

I am using the top material tab bar, and one tab contains a stack navigator, like:
Category Screen -> Sub-Category screen -> Details page

When I goes to Sub-category or Details screen, then **iOS** swipe back is not working. Everything working fine in Android.
Also tried @JoniVR solution, it is also not working.

From package.json
`"react-native-tab-view": "^3.1.1"`
`"react": "17.0.2"`
`"react-native": "0.66.4"`
`"@react-navigation/drawer": "^6.1.8"`
`"@react-navigation/material-top-tabs": "^6.0.6"`
`"@react-navigation/native": "^6.0.6"`
`"@react-navigation/native-stack": "^6.2.5"`

Ant other suggestions to fix this?

**Comment by Hirbod** [comment]
I can confirm this. While I try to swipe gesture back, I just receive "Sending `onAnimatedValueUpdate` with no listeners registered.

**Comment by JoniVR** [comment]
@RajeshSFS Have you done a `pod install` after removing your `Podfile.lock` and `Pods` folder? You need to clean and reinstall pods for this iirc.

**Comment by RajeshSFS** [comment]
Yes @JoniVR I tried removing `podfile.lock` and `Pods` folder. Even also tried removing `node_modules` folder.

There are little change, before I am getting this warning `Sending onAnimatedValueUpdate with no listeners registered` on swipe. But now this warning is not coming.

**Comment by achuinard** [comment]
Try using the regular, non-native stack navigator. I think it’ll return the swipe gesture, but I’m unsure of other pros / cons on using native vs. non-native.

**Comment by nateguy** [comment]
Any updates on this bug?

**Comment by bintoll** [comment]
Also face this issue

**Comment by ramiel1999** [comment]
same here. can not swipe back when inside stack navigator

**Comment by ramiel1999** [comment]
> FYI, downgrading `react-native-tab-view` to `v2.16.0` seems to resolve the issue for now (probably related to [react-navigation/react-navigation#10083](https://github.com/react-navigation/react-navigation/issues/10083)), for those who are running into the same issue...

Downgrading works, but I really hope it can be improved in further releases. I dont want to stay at an old version

**Comment by intergalacticspacehighway** [comment]
Created a PR in pager view. I think it should fix this issue since it uses pager-view under the hood. Can someone please verify? https://github.com/callstack/react-native-pager-view/pull/500#issuecomment-1094018750

**Comment by giangpro93** [comment]
> 

I tested it and it doesn't seem to work.

**Comment by adscud** [comment]
Any updates about that ?

**Comment by ramiel1999** [comment]
@intergalacticspacehighway still can not swipe back

**Comment by intergalacticspacehighway** [comment]
@ramiel1999 updating pager view to 5.4.24 fixes the issue in OP's repo. Also created the PR in original repro here. https://github.com/mtflud/react-native-tab-view-swipe-back-repro/pull/1

https://user-images.githubusercontent.com/23293248/173184580-d3d62194-a752-4b3a-b46d-d3feaaad5309.mov

@mtflud can you please confirm?

@ramiel1999 
Are you using expo? If yes, updating pager-view might not work as it uses the previous version.
Are you using `fullScreenSwipeEnabled` in Screens? It won't work with that.

**Comment by ramiel1999** [comment]
I am using expo-dev-client, but I am using stack instead of native-stack which doesnt seem to work. I can confirm that native-stack does work but not stack

**Comment by okwasniewski** [comment]
After upgrading to expo v46 and `react-native-pager-view` to `5.4.24` issue is solved. Here is a snack: https://snack.expo.dev/TGFrSAyUkq

**Comment by IngyuTae** [comment]
> After upgrading to expo v46 and `react-native-pager-view` to `5.4.24` issue is solved. Here is a snack: https://snack.expo.dev/TGFrSAyUkq

Are you using @react-navigation/stack or @react-navigation/native-stack?

**Comment by mikefogg** [comment]
@IngyuTae I'm seeing the same issue and using `@react-navigation/stack`.
