### ISSUE TITLE
TabView Crashed on react-native-pager-view upgrade

### ISSUE THREAD

**Issue by EM-Sabeel** [satya164/react-native-tab-view#1290]
### Current behavior

When i upgraded pager view to  `"react-native-pager-view": "^6.0.0-rc.0"`, I'm getting below error.
<img src="https://user-images.githubusercontent.com/80961628/140075498-34445912-2cd0-4b41-a0c0-53406d4b8b2b.JPEG" width="300"  />

Currently, you using this method.
```js
import ViewPager from 'react-native-pager-view';

const AnimatedViewPager = Animated.createAnimatedComponent(ViewPager);

```

But, With the latest version of PageView, You should import like this
```js
import {PagerView} from 'react-native-pager-view';

const AnimatedViewPager = Animated.createAnimatedComponent(PagerView);

```

### Expected behavior

The TabView should work with the latest pageview, can you release a beta version for this to work.

### Reproduction

https://snack.expo.dev/@sabeelkm/tabview

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  | 3.1.1
| react-native-pager-view                | 6.0.0-rc.0
| react-native                           | 0.64
| expo                                   | Nil
| node                                   | 14.17.3
| npm                             | 6.14.13

**Comment by EM-Sabeel** [comment]
I need Lazy Pager View and is available on this (6.0.0-rc.0) Version only.

**Comment by EM-Sabeel** [comment]
@satya164 any updates

**Comment by samadritsarkar2** [comment]
I am also facing the same issue.

**Comment by samadritsarkar2** [comment]
I got the solution to this problem here [#654 ](https://github.com/satya164/react-native-tab-view/issues/654#issuecomment-444470652)

**Comment by EM-Sabeel** [comment]
@samadritsarkar2  That solution is not working for this issue

**Comment by EM-Sabeel** [comment]
> Currently, you using this method.
> 
> ```js
> import ViewPager from 'react-native-pager-view';
> 
> const AnimatedViewPager = Animated.createAnimatedComponent(ViewPager);
> ```
> 
> But, With the latest version of PageView, You should import like this
> 
> ```js
> import {PagerView} from 'react-native-pager-view';
> 
> const AnimatedViewPager = Animated.createAnimatedComponent(PagerView);
> ```

@samadritsarkar2 this is the solution

**Comment by samadritsarkar2** [comment]
That solution worked for me.

`const renderScene = SceneMap({
  first: AddRoom,
  second: AddImages,
  third: AddDetails,
});`

`const [routes] = useState([
    {key: 'first', title: 'Basic Room Info'},
    {key: 'second', title: 'Add Images'},
    {key: 'third', title: 'Final Details'},
  ]);`


the _key_ fields should be same.

**Comment by iaminarush** [comment]
What I did was forking the react-native-pager-view and changing the [index.tsx](https://github.com/iaminarush/react-native-pager-view/blob/next/src/index.tsx) in the next branch to export default PagerView like the previous versions and install the library using the github repo.

**Comment by okwasniewski** [comment]
RC of pager-view `6.0.0` is not yet supported. Closing this
