### ISSUE TITLE
How can i add a padding to the scroll tab container?

### ISSUE THREAD

**Issue by likeSo** [satya164/react-native-tab-view#1304]
### Current behavior

![image](https://user-images.githubusercontent.com/12247340/147183721-bf6404ad-3c22-4d99-95ad-add269acd3e4.png)
I made this by adding `marginHorizontal: 16` to `tabBarContentContainerStyle` and `tabBarIndicatorContainerStyle`

But when i swipe to the right, the tab bar did not show completely:
![image](https://user-images.githubusercontent.com/12247340/147186564-f412c91c-2a36-4491-8a2e-eb66e6994381.png)

I am using react-navigation-material-top-tab

### Expected behavior

- **I need padding on both the left and right sides.**
- ** Another question: **How can i control the indicator's width to follow the label's width? For now, the indicator is wider than the label

### Reproduction

https://snack.expo.dev/@likeso/react-navigation-tab-issue

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  |^3.1.1
| react-native-pager-view                |5.4.6
| react-native                           |0.64.3
| expo                                   |^43.0.0
| node                                   |v14.17.5
| npm or yarn                            |yarn

**Comment by likeSo** [comment]
It's been almost a month, can anybody teach me how can i do this? Please help

**Comment by shubhanus** [comment]
had done this way

```javascript
                   indicatorStyle={{
                        left: INDICATOR_WIDTH_MARGIN_MAP[
                            props.indicatorWidth || 'full'
                        ]
                   }}
                   renderIndicator={indicatorProps => {
                        const width =
                            indicatorProps.getTabWidth(index) -
                            INDICATOR_WIDTH_MARGIN_MAP[indicatorWidth] * 2;
                        return (
                            <TabBarIndicator
                                {...indicatorProps}
                                width={width}
                            />
                        );
                    }}
```

**Comment by okwasniewski** [comment]
Closing this, since @shubhanus provided solution.
