### ISSUE TITLE
app flashed quit

### ISSUE THREAD

**Issue by SunyanLBJ23** [satya164/react-native-tab-view#1305]
### Current behavior

I quickly moved between tabar's screens, and then I triggered the naviation.goBack() method, and the app flashed quit. 

react-native version 0.64.2, 
@react-navigation/native version 6.0.6,
 react-native-tab-view version 3.1.1

### Expected behavior

not quit

### Reproduction

none

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  | 3.1.1
| react-native-pager-view                | 5.4.9
| react-native                           | 0.64.2
| expo                                   | none
| node                                   | 14.18.1
| npm or yarn                            | yarn

**Comment by likeSo** [comment]
This is a bug in this react-native-pager-view: https://github.com/callstack/react-native-pager-view/issues/458
You can visit and focus on that
