### ISSUE TITLE
Jcenter needs to be removed

### ISSUE THREAD

**Issue by AdhamMahmoud98** [satya164/react-native-tab-view#1309]
### Current behavior

Jcenter is not stable at the moment and its support will be discontinued. I am trying to compile my app locally and I getting this issue due to jcenter

Could not download kotlin-build-common-1.5.30.jar (org.jetbrains.kotlin:kotlin-build-common:1.5.30)
> Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-build-common/1.5.30/kotlin-build-common-1.5.30.jar'. > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-build-common/1.5.30/kotlin-build-common-1.5.30.jar'. Received status code 502 from server: Bad Gateway

### Expected behavior

app builds successfully

### Reproduction

https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-build-common/1.5.30/kotlin-build-common-1.5.30.ved

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by satya164** [comment]
This library doesn't include any native code. Please open the issue in the relevant library's repo.
