### ISSUE TITLE
Tabs are not clickable on iOS after click on active tab

### ISSUE THREAD

**Issue by chshanovskiy** [satya164/react-native-tab-view#1322]
### Current behavior

When I click on currently active tab, all tabs are stopped to work. Nothing happens, when I click other tabs. But swipe is still working, for example. Only tab clicks stop working. And only on iOS device and iOS Simulator (android works fine).

Reproduction is superminimal – just fresh react-native with two dependencies and full code from example.
Also there is a video demo – https://github.com/chshanovskiy/tabview/blob/develop/tabview.gif

### Expected behavior

Tabs are still clickable on iOS after click on active tab

### Reproduction

https://github.com/chshanovskiy/tabview

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  | 3.1.1
| react-native-pager-view                | 5.4.11
| react-native                           | 0.67.3
| node                                   | 16.13.1
| yarn                            | 1.22.17

**Comment by alantoa** [comment]
same issue, when use [react-native-pager-view](https://github.com/callstack/react-native-pager-view) v5.4.11.

**Comment by alantoa** [comment]
@chshanovskiy Hi!
The reason for this problem is `react-native-pager-view`.
I fixed it, You can see PR https://github.com/callstack/react-native-pager-view/pull/527.
Or you could try my fork lib, `yarn add git+https://github.com/alantoa/react-native-pager-view`.

**Comment by chshanovskiy** [comment]
@alantoa looks great, I'll try it

**Comment by jixt** [comment]
The fix of @alantoa fixes this issue, but brings back an old issue that crashes the app after rapid switching. I have created another solution that solves this issue and also makes sure the app doesn't crash when doing rapid switching between the tabs. You can find it here: 

https://github.com/callstack/react-native-pager-view/pull/529

**Comment by alantoa** [comment]
@jixt You are right!
Ty!

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/releases/tag/v5.4.12

**Comment by ElicaInc** [comment]
> https://github.com/callstack/react-native-pager-view/releases/tag/v5.4.12

Works great!
