### ISSUE TITLE
OnIndexChange not working if index is zero

### ISSUE THREAD

**Issue by shivamKredX** [satya164/react-native-tab-view#1335]
### Current behavior

OnChangeIndex is not working if index is 0

### Expected behavior

OnChangeIndex should return new changed index

### Reproduction

https://www.npmjs.com/package/react-native-tab-view

### Platform

- [X] Android
- [X] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by alan19031216** [comment]
any update? I also got this issues
