### ISSUE TITLE
Doesn't work with `SafeAreaView` on Android only

### ISSUE THREAD

**Issue by KrisLau** [satya164/react-native-tab-view#1338]
### Current behavior

I'm wrapping the `TabView` in a `SafeAreaView` and it doesn't seem to work on Android.
![image](https://user-images.githubusercontent.com/46275463/165396908-b7f6778e-5270-431a-8c9a-8c42649b70a5.png)
![image](https://user-images.githubusercontent.com/46275463/165396991-39697d08-0c30-496a-89cd-fdd75d402ca0.png)

I tried repro-ing in the snack but it doesn't seem to be the same in the snack

### Expected behavior

It should like how it does in iOS:
![image](https://user-images.githubusercontent.com/46275463/165397257-e5f643fe-6bee-49a9-81c6-b64494423e0c.png)

### Reproduction

https://snack.expo.dev/auZcPPHTe

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  | 3.1.1
| react-native-pager-view                | 5.4.9
| react-native                         | 0.64.3
| expo                                   | N/A
| node                                   | 14.16.1
| npm or yarn                            | 1.22.10

**Comment by KrisLau** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `expo`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.
> 
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `react-native-pager-view` (found: `5.4.9`, latest: `5.4.15`)
> * `react-native` (found: `0.64.3`, latest: `0.68.1`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Not upgrading because i currently use the expo-unimodules package and `expo` causes problems with my client database

**Comment by szymonrybczak** [comment]
As official React Native documentation says about [SafeAreaView](https://reactnative.dev/docs/safeareaview) -  `It is currently only applicable to iOS devices with iOS version 11 or later.`, so it isn't any problem with `react-native-tab-view`, to achieve your goal you can use e.g. `StatusBar`.
