### ISSUE TITLE
iOS crashes if index in navigationState is updated too quickly

### ISSUE THREAD

**Issue by jasonkv** [satya164/react-native-tab-view#1344]
### Current behavior

On iOS (Android works fine) there is a hard crash (no logs) that happens if **index** in **navigationState** is updated too quickly.

This happens when a user might press a button to switch to the next tab  too quickly (multiple times in a row):

Example code to reproduce (roughly):
```

import * as React from 'react';
import { View, useWindowDimensions, Button } from 'react-native';
import { TabView, SceneMap } from 'react-native-tab-view';

const FirstRoute = () => (
  <View style={{ flex: 1, backgroundColor: '#ff4081' }} />
);

const SecondRoute = () => (
  <View style={{ flex: 1, backgroundColor: '#673ab7' }} />
);

const renderScene = SceneMap({
  0: FirstRoute,
  1: SecondRoute,

  2: FirstRoute,
  3: SecondRoute,
  /* ... a few more entries */
});

export default function TabViewExample() {
  const layout = useWindowDimensions();

  const [index, setIndex] = React.useState(0);
  const [routes] = React.useState([
    { key: 0, title: 'First' },
    { key: 1, title: 'Second' },
    { key: 3, title: 'Third' },
    { key: 4, title: 'Fourth' },
      /* ... a few more entries */

    
  ]);
  const routesCount = routes?.length;
  return (<View>
  
    
    <Button 
        onPress={() => setIndex(Math.max(index - 1, 0))} 
        disabled={index === 0}
      >
        Backwards
      </Button>
      <Button 
        onPress={() => setIndex(Math.min(index + 1, routesCount - 1)} 
        disabled={index === routesCount - 1}
      >
          Forward
      </Button>
    
        <TabView
          navigationState={{ index, routes }}
          renderScene={renderScene}
          onIndexChange={setIndex}
          initialLayout={{ width: layout.width }}
        />
    </View>
  );
}
```

The problem seems to be in a library `react-native-pager-view` used inside `PagerViewAdapter`. This component calls: 
`    pagerRef.current?.setPage(index);
`

Which if switched to:
`    pagerRef.current?.setPageWithoutAnimation(index);`

With this change, it seems to work  fine but lacks the animation.

Note: There is no crash if navigating through the tabs via quickly swiping instead of  pressing the buttons to navigate through the tabs. 

### Expected behavior

For it to not crash.

### Reproduction

Example Provided above

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  | ^3.1.1
| react-native-pager-view          5.4.9      |
| react-native                   0.64.3        |
| expo                                ~44.0.0   |
| node                                   |
| npm or yarn                            |

**Comment by nitin-jotwani-fc** [comment]
getting same issue in ios for version 3.1.1
