### ISSUE TITLE
Does not scroll to latest content

### ISSUE THREAD

**Issue by jeet-mehta** [satya164/react-native-tab-view#1359]
### Current behavior

I have a tab in my home screen. There are total two tabs. One is Home screen and second is Settings screen. In my home screen I have to fire a api to get data. Now when I add pagination in that tab ( i.e. HomeScreen ) I get the data and the content is also reflected in the flatlist. But the issue is that the flatlist is automatically scrolled to the top. 

```
const onEndReachedPeople = () => {
        api.search(requestObject)
            .then(res => {
                if (res.code === 200) {
                    setPeopleData([...peopleData, ...res.data.user])
                }
            })
    }

const renderPeopleTab = ({ item }: any) => {
                return (
            <View style={{ marginVertical: 10 }}>
                <PeopleTile
                    userInfo={item}
                    location={item.location}
                    title={item.userName}
                    profileURL={item.profilePic}
                    isFollowing={item.following}
                    onPressFollow={onPressFollow}
                    onPressUnfollow={onPressUnFollow}
                    onPressTile={onPressTile}
                />
            </View>
        )
    }

 const Tab = () => {
        return (
            <FlatList
                data={peopleData}
                renderItem={renderPeopleTab}
                style={ {
        flex: 1,
    }}
                contentContainerStyle={{
        flexGrow: 1,
        paddingHorizontal: smartScale(15),
        paddingBottom: smartScale(100)
    }}
                onEndReached={onEndReachedPeople}
                onEndReachedThreshold={0.5}
            />
        )
    }

const renderScene = ({ route }: { route: { key: string } }) => {
        switch (route.key) {
            case 'people':
                return <Tab />
            case 'groups':
                return <ComingSoon />
            default:
                return null
        }
    }

return (
           <TabView
                    swipeEnabled={true}
                    navigationState={{ index, routes }}
                    renderScene={renderScene}
                    onIndexChange={setIndex}
                    initialLayout={{ width: WINDOW.width }}
            />
)
```

### Expected behavior

Here the flatlist should not scroll to top and maintain the scroll position. 

### Reproduction

na

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  |  ^3.1.1
| react-native-pager-view                | ^5.4.7
| react-native                           | 0.66.1

**Comment by jiyuan12354** [comment]
I think you just encounter the render issue, Though I am using version 2.16, I still want to suggest you to use `SceneMap` to wrapper you routes
...
```

import {
  TabView
  SceneMap,
  ...
} from 'react-native-tab-view';
...
const renderScene = SceneMap([your sceneMap);
...

  return (
    <TabView
      ...
      renderScene={renderScene}
      ...
    />
  );
```
Each value of your sceneMap should be a named function component or class component， DONOT use `anonymous function`

**Comment by Barragan17** [comment]
I've used scenemap and it is still not working, after the api call it still scroll up top, not to it's last position

**Comment by OPEN-9** [comment]
I also encountered this problem with flatList
