### ISSUE TITLE
Tab label gets faded out while swiping

### ISSUE THREAD

**Issue by vinaygregoryjohn183** [satya164/react-native-tab-view#1366]
### Current behavior

Tab label gets faded while swiping between tabs.

### Expected behavior

Tab label should not fade-out while swiping between tabs.

### Reproduction

Sharing the code below

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view  2.16.0   |
| react-native  0.66.4 |
| node 14.17.0 |
| npm or yarn  6.14.14 |
Code: 

import React from 'react';
import {
    SceneMap,
    TabBar,
    TabBarIndicator,
    TabView,
} from 'react-native-tab-view';

import {TabLabelProps, TabsProps} from './TabsTypes';
import {Text} from '../text';
import {Icon} from '../icons';
import {INDICATOR_WIDTH_MARGIN_MAP} from './constants';
import {useTabStyles} from './useTabsStyles';

const TabLabel = ({focused, title}: TabLabelProps) => {
    return (
        <Text
            fontColor={focused ? 'primary' : 'grayPrimary'}
            fontWeight={focused ? 'bold' : 'regular'}>
            {title}
        </Text>
    );
};

const Tabs = ({
    indicatorWidth
}: TabsProps) => {
    const styles = useTabStyles(indicatorWidth);

const renderScene = useCallback(
    ({ route }: { route: { key: string } }) => {
      switch (route.key) {
        case CustomerDetailsTabKeys.Summary:
          return <CustomerOrderSummary customerData={customerData} />;
        case CustomerDetailsTabKeys.Order_History:
          return (
            <CustomerOrderHistory storeId={storeId} />
          );
        default:
          return null;
      }
    },
    [customerData, storeId]
  );

  const tabRoutes = useMemo(() => {
    return [
      {
        key: CustomerDetailsTabKeys.Summary,
        title: translate('screen:customer-details.text:summary'),
        testID: accessibilityTestID.customerDetails.summaryTab
      },
      {
        key: CustomerDetailsTabKeys.Order_History,
        title: translate('screen:customer-details.text:order-history'),
        testID: accessibilityTestID.customerDetails.orderHistoryTab
      }
    ];
  }, []);

const onIndexChange = useCallback(
    (index) => {
      if (tabRoutes[index].key === CustomerDetailsTabKeys.Order_History) {
        EventEmitter.emit(EventType.MerchantOrderListVisited, {
          source: ScreenName.CUSTOMER_DETAILS
        });
      }
      if (setRouteIndex) setRouteIndex(index);
    },
    [setRouteIndex, tabRoutes]
  );

const initialLayout = { width: metrics.screenWidth };

const navigationState={{ index: routeIndex, routes: tabRoutes }}

    return (
        <TabView
            renderTabBar={tabBarProps => (
                <TabBar
                    navigationState={navigationState}
                    renderScene={renderScene}
                    onIndexChange={onIndexChange}
                    initialLayout={initialLayout}
                    scrollEnabled={true}
                    indicatorStyle={styles.indicator}
                    renderIcon={({route, focused}) => {
                        if (route.icon) {
                            return (
                                <Icon
                                    name={
                                        focused && route.focusedIcon
                                            ? route.focusedIcon
                                            : route.icon
                                    }
                                    color={focused ? 'primary' : 'grayPrimary'}
                                    size={24}
                                />
                            );
                        }
                        return null;
                    }}
                    renderIndicator={indicatorProps => {
                        const tabWidth = indicatorProps.getTabWidth(
                            navigationState.index,
                        );
                        const width =
                            tabWidth -
                            INDICATOR_WIDTH_MARGIN_MAP[
                                indicatorWidth || 'full'
                            ] *
                                2;
                        return (
                            <TabBarIndicator
                                {...indicatorProps}
                                width={width}
                            />
                        );
                    }}
                    style={styles.tab}
                    renderLabel={
                            ({route, focused}) => (
                                  <TabLabel
                                      focused={focused}
                                      title={route.title}
                                  />
                              )
                    }
                />
            )}
        />
    );
};
export {Tabs, SceneMap, TabLabel};

![Screenshot_1656651436](https://user-images.githubusercontent.com/82080446/176840216-28ac50ad-3994-418d-b6bb-db820d759a0d.png)

**Comment by gokugen** [comment]
Hello any updates ?

**Comment by okwasniewski** [comment]
Hey @gokugen, can you provide a minimal reproduction of this issue using [this](https://snack.expo.dev/@satya164/react-native-tab-view-quick-start) snack?
