### ISSUE TITLE
How to not rerender all tabs when swipe to another tab ?

### ISSUE THREAD

**Issue by shop-fluencer** [satya164/react-native-tab-view#1368]
### Current behavior

```
const SearchMain = ({}: ISearchMain) => {
  const { t } = useTranslation();
  const [index, setIndex] = React.useState(0);
  const [routes] = React.useState([
    { key: 'products', title: 'Produkte'},
    { key: 'shops', title: 'Shops' },
  ]);

  const renderScene = ({ route }: { route: { key: string; title: string; } }) => {
    switch (route.key) {
      case 'products':
        return <SearchProductListRLV index={index} />
      case 'shops':
        return <ShopsCardRLV index={index} />;
      default:
        return null;
    }
  }
  return (
    <TabView
      lazy
      navigationState={{ index, routes }}
      renderScene={renderScene}
      onIndexChange={setIndex}
      keyboardDismissMode='auto'
      initialLayout={initialLayout}
      renderTabBar={renderTabBar}
    />
  );
```

### Expected behavior

My tabs are every time rerender when I swiping to a tab. How can I prevent this ?

### Reproduction

dd

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view               3.1.1   |
| react-native-pager-view           5.4.15     |
| react-native                           |
| expo                                  0.45 |
| node                                   |
| npm or yarn                            |

**Comment by satya164** [comment]
You're passing `index` to your tabs which changes when you swipe, there's no way to prevent re-render if you need to pass `index` - the component needs to re-render to get the new index. If you don't need `index`, then remove it and apply `React.memo` to your components or use `SceneMap`.
