### ISSUE TITLE
Can i jumpTo withoutAnimation?

### ISSUE THREAD

**Issue by ht19** [satya164/react-native-tab-view#1371]
### Description

Can i jumpTo another page view withoutAnimation like react-native-pager-view setPageWithoutAnimation method?

### Inspirations & examples

PagerView.current.setPageWithoutAnimation(index)

**Comment by okwasniewski** [comment]
Thanks for your suggestion. At the moment it's not possible, hopefully someone will take a look at this and implement this. I'm happy to review the PR 💪

**Comment by okwasniewski** [comment]
Hey @ht19,

This have been implemented by @szymonrybczak in #1388 and released in `react-native-tab-view@3.2.1` 👍🏻
