### ISSUE TITLE
IOS Not full animation to the pressed tab when keyboard is opened

### ISSUE THREAD

**Issue by Kruglyanski** [satya164/react-native-tab-view#1373]
### Current behavior

Animation between tabs not scrolls to the end.  The onIndexChange  not fires as a result. Animation ends if click on content

https://user-images.githubusercontent.com/45219732/182527044-70fa1bcb-52dd-46fb-9c66-c23b91732553.mp4

### Expected behavior

Animation ends, onIndexChange fires

### Reproduction

-

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                         | version |  
| -------------------------------------- | ------- |  
| react-native-tab-view                  | 3.1.1      
| react-native-pager-view                |  5.4.25
| react-native                           | 0.64.2
| expo                                   | no
| node                                   | 18.7.0
| npm or yarn                            | npm 8.15.0

**Comment by steffenabel** [comment]
I'm experiencing the same issue with version 3.1.1 and the current RN version (0.69.1) when using a textinput with autofocus enabled. A downgrade to version 2.16.0 fixes the issue.

**Comment by okwasniewski** [comment]
Hey @Kruglyanski can you add a snack reproducing this?
