### ISSUE TITLE
Tab View inside Flatlist not shown content

### ISSUE THREAD

**Issue by gurbela** [satya164/react-native-tab-view#1374]
### Current behavior

When I switched tabs ( inside Flatlist) the content was not shown.

Without Flatlist it works fine, any ideas on how to fix it?
 (the scrollable view is required)
 
 
 

### Expected behavior

 current version: 
 "react-native-pager-view": "5.4.25",
 "react-native-tab-view": "3.1.1",
 
  I was also using the old version: "react-native-tab-view": "2.16.0", but when I rotate the phone, the scene view is not looking correctly, which is fixed in "3.1.1" version

### Reproduction

https://snack.expo.dev/oPaWEf5_-

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  | 3.1.1
| react-native-pager-view                | 5.4.25
| react-native | 0.64.2

**Comment by szymonrybczak** [comment]
This is fixed in https://github.com/satya164/react-native-tab-view/pull/1383 and it'll soon merged into `main` cc. @okwasniewski

**Comment by okwasniewski** [comment]
What's the point of embedding `tab-view` inside a flatlist? This looks really off to me by rendering in with `renderItem`. If you want to render `tab-view` inside scroll view you can refer to this solution: #1349.

**Comment by okwasniewski** [comment]
Closing this as stale.
