### ISSUE TITLE
Collapsible Header

### ISSUE THREAD

**Issue by KrisLau** [satya164/react-native-tab-view#1375]
### Description

I'm hoping to be able to do something like this: https://github.com/zyslife/react-native-head-tab-view or like what this guy describes: https://github.com/software-mansion/react-native-gesture-handler/issues/492#issuecomment-927353039. It's really hard to implement this manually since the nested scroll view in the tab view seems to conflict with PanGestureHandler

### Alternatives

- Using `PanGestureHandler` but it doesn't work because tab view already has a `ScrollView` and then the tab scenes I pass in also have a `ScrollView`
- https://github.com/zyslife/react-native-head-tab-view but it hasn't been updated since June last year

### Inspirations & examples

- Tiktok Profile header: https://github.com/software-mansion/react-native-gesture-handler/issues/492#issuecomment-927353039
- https://github.com/zyslife/react-native-head-tab-view

**Comment by KrisLau** [comment]
https://github.com/satya164/react-native-tab-view/pull/1079#issuecomment-815261996

**Comment by KrisLau** [comment]
Also if you need more maintainers @satya164, would you be open to maybe opening an issue to recruit and officially add maintainers? There are a couple issues here where people are offering to maintain the library plus once that issue is open I would also be able to submit this repo to https://github.com/pickhardt/maintainers-wanted

**Comment by okwasniewski** [comment]
@KrisLau I've added my comment on the PR. Hopefully we can merge this feature soon 👍🏻

**Comment by KrisLau** [comment]
@okwasniewski Thank you!

**Comment by okwasniewski** [comment]
After consulting this with @satya164 we decided that we want to keep the library as small as possible (and easy to maintain) so I'm closing this issue.
