### ISSUE TITLE
Extra height on tab view with fabric enabled

### ISSUE THREAD

**Issue by luutruong** [satya164/react-native-tab-view#1398]
### Current behavior

<img width="395" alt="Screen Shot 2022-10-16 at 08 43 51" src="https://user-images.githubusercontent.com/3833024/196013944-8f194ce3-202e-4f24-b568-88dca758ff6c.png">

### Expected behavior

Should not have extra height.

Without fabric; it works fine.

### Reproduction

Usage:

```
  const renderScene = useCallback(
    (info: {route: {key: string}}) => {
      return (
        <Foo />
      );
    },
    [routes, tabIndex],
  );

  const tabBarStyle = useMemo<StyleProp<ViewStyle>>(() => {
    return {
      backgroundColor: colors.contentBackgroundColor,
      paddingVertical: 0,
    };
  }, [colors.contentBackgroundColor]);
  const textStyle: any = useMemo(() => {
    return {
      fontWeight: '600',
    };
  }, []);
  const renderTabLabel = useCallback(
    (info: {route: {title: string}}) => {
      return <Text style={textStyle}>{info.route.title}</Text>;
    },
    [textStyle],
  );
  const renderTabBar = useCallback(
    (tabBarProps: any) => (
      <TabBar
        {...tabBarProps}
        style={tabBarStyle}
        renderLabel={renderTabLabel}
        indicatorStyle={{backgroundColor: colors.textColor}}
        scrollEnabled
        tabStyle={{width: 'auto'}}
      />
    ),
    [renderTabLabel, tabBarStyle, colors.textColor],
  );

  return (
    <TabView
      lazy
      onIndexChange={setTabIndex}
      navigationState={{index: tabIndex, routes}}
      renderScene={renderScene}
      renderTabBar={renderTabBar}
      initialLayout={{width: dimensions.width}}
    />
  );
```

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  | ^3.3.0
| react-native-pager-view                |  ^6.1.0-rc.1
| react-native                           | 0.70.3
| expo                                   |
| node                                   | 16
| npm or yarn                            | yarn

**Comment by okwasniewski** [comment]
Hey @luutruong 

Thanks for reporting this bug, can you provide a screenshot comparing both architectures?

**Comment by luutruong** [comment]
Hi @okwasniewski 

I attached screenshot in description of issue.

- Old version:
 (react-native: 0.70.3 react-native-tab-view: ^3.3.0 react-native-pager-view: ^6.0.1)
<img width="395" alt="Screen Shot 2022-10-16 at 08 43 51" src="https://user-images.githubusercontent.com/3833024/196027608-007f4818-4ff8-4c5a-8abc-72fb52e245ec.png">


- Fabric enabled:
https://user-images.githubusercontent.com/3833024/196013944-8f194ce3-202e-4f24-b568-88dca758ff6c.png

**Comment by okwasniewski** [comment]
Linking the same issue from `react-native-pager-view`: https://github.com/callstack/react-native-pager-view/issues/618

**Comment by troZee** [comment]
Could you check this version of RNPV https://github.com/callstack/react-native-pager-view/releases/tag/v6.1.0-rc.2

**Comment by okwasniewski** [comment]
Closing this, since it was resolved in [react-native-pager-view](https://github.com/callstack/react-native-pager-view/releases/tag/v6.1.0-rc.2)
