### ISSUE TITLE
On chaging tab Previous tab functionality should stop 

### ISSUE THREAD

**Issue by harishbabu0419** [satya164/react-native-tab-view#953]
# No Template

👉 Please follow one of the issue templates provided by the repo - if you are seeing this message, it means you haven't.

If you don't follow the issue template, we may immediately close it.

**Comment by woomedya** [comment]
same

**Comment by SergeyMyssak** [comment]
I also didn't find a solution to this problem [#933](https://github.com/react-native-community/react-native-tab-view/issues/933)

**Comment by satya164** [comment]
Closing due to incomplete issue template.
