### ISSUE TITLE
 Unable to resolve module `./ScrollPager`

### ISSUE THREAD

**Issue by eramudeep** [satya164/react-native-tab-view#963]
### Current behaviour
throwing error :
Unable to resolve module `./ScrollPager` 

### Environment
 OS: Windows 10
      CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
      Memory: 5.17 GB / 15.94 GB
    Binaries:
      Node: 10.16.3 - D:\node\node.EXE
      Yarn: 1.19.0 - D:\yarn\bin\yarn.CMD
      npm: 6.9.0 - D:\node\npm.CMD

| software                     | version
react-native-cli: 2.0.1
react-native: 0.59.9
| react-native-tab-view        | ^2.10.0
| react-native-gesture-handler | ^1.5.6
| react-native-reanimated      | 1.7.0
| node                         | v10.16.3
| npm                   | 6.9.0

**Comment by eramudeep** [comment]
*Its looks like a Machine spacific problem*
in tried on another machine. the same code worked fine.
not understanding why.

**Comment by tywong7** [comment]
Run `react-native start --reset-cache` worked for me
