### ISSUE TITLE
export { default as TabView, Props as TabViewProps } from './TabView' in JS build

### ISSUE THREAD

**Issue by thecodehunter** [satya164/react-native-tab-view#969]
# Current behaviour

WARNING in JS build:
export { default as TabView, Props as TabViewProps } from './TabView' in JS build
Also the same in TabBar, i checked the TS code and looks good to me, the prop is exported correctly so it looks like a build problem.

### Expected behaviour
No Warnings, Props should be exported on the JS build.

### Screenshots (if applicable)

![Screenshot from 2020-02-19 11-24-13](https://user-images.githubusercontent.com/2933118/74853386-dd412080-530b-11ea-841e-e83b5992498d.png)

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | web
| react-native                 | 0.61.4
| react-native-tab-view        | 2.13.0
| react-native-gesture-handler | 1.5.6
| react-native-reanimated      | 1.4.0
| node                         | 10.16
| npm or yarn                  | 6.9

**Comment by raajnadar** [comment]
As a temporary workaround use version `2.10.0` or `2.10.2`

**Comment by patrickgodinho** [comment]
I have some problem using react-navigation-tabs. Is there any solution?

**Comment by MathieuUrstein** [comment]
@patrickgodinho here is a few solutions:
- Hack your package-lock.json to use a working version as mentioned by @raajnadar ([example](https://stackoverflow.com/a/48524488/2544631))
- Patch the package using [patch-package](https://github.com/ds300/patch-package)

Example of patch:
Path: `patches/react-native-tab-view+2.13.0.patch`
```Diff
diff --git a/node_modules/react-native-tab-view/lib/module/index.js b/node_modules/react-native-tab-view/lib/module/index.js
index 629b89f..ed34cc0 100644
--- a/node_modules/react-native-tab-view/lib/module/index.js
+++ b/node_modules/react-native-tab-view/lib/module/index.js
@@ -1,2 +1,2 @@
-export{default as TabView,Props as TabViewProps}from'./TabView';export{default as TabBar,Props as TabBarProps}from'./TabBar';export{default as SceneMap}from'./SceneMap';export{default as ScrollPager}from'./ScrollPager';export{Route,NavigationState,SceneRendererProps}from'./types';
+export{default as TabView}from'./TabView';export{default as TabBar}from'./TabBar';export{default as SceneMap}from'./SceneMap';export{default as ScrollPager}from'./ScrollPager';export{Route,NavigationState,SceneRendererProps}from'./types';
 //# sourceMappingURL=index.js.map
```

**Comment by satya164** [comment]
Should be fixed in latest version.
