### ISSUE TITLE
YellowBox warning from TabView/Pager component during tests

### ISSUE THREAD

**Issue by frantjc** [satya164/react-native-tab-view#970]
### Current behaviour

The library appears to work as expected on an emulator.  However, during tests, there is YellowBox error (which I know how to solve) and two YellowBox warnings that get thrown from the Pager component:

![Screen Shot 2020-02-19 at 3 48 47 PM](https://user-images.githubusercontent.com/39865011/74874867-5ef67580-532f-11ea-9b3f-e2ebaf618d06.png)

I think this is caused by the interaction between those components and react-native-reanimated's mock, but I haven't been able to solve the problem.

### Expected behaviour

I'd like for these warnings/errors to not appear during the testing process.

![Screen Shot 2020-02-19 at 3 48 47 PM](https://user-images.githubusercontent.com/39865011/74874867-5ef67580-532f-11ea-9b3f-e2ebaf618d06.png)

### Code sample

For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

App.js
```javascript
import React, {useState} from 'react';
import {View, Dimensions} from 'react-native';

import {TabView, SceneMap, TabBar} from 'react-native-tab-view';

const FirstRoute = () => (
  <View style={{ backgroundColor: '#ff4081' }} flex={1} />
);

const SecondRoute = () => (
  <View style={{ backgroundColor: '#673ab7' }} flex={1} />
);

const App = () => {
  const [index, setIndex] = useState(0);
  const [routes] = useState([
    { key: 'first', title: 'First' },
    { key: 'second', title: 'Second' },
  ]);

  const renderScene = SceneMap({
    first: FirstRoute,
    second: SecondRoute,
  });

  const navigationState = {index, routes};

  const initialLayout = { width: Dimensions.get('window').width };

  return (
    <View flex={1}>
      <TabView
        renderScene={renderScene}
        initialLayout={initialLayout}
        navigationState={navigationState}
        onIndexChange={setIndex}
        renderTabBar={props => ( // unnecessary, this is the default implementation
          <TabBar {...props} />
        )}
      />
    </View>
  );
}

export {App};
```

package.json
```
{
  "name": "reactNativeTabViewIssue",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios --port 3000 --simulator 'iPhone 8 Plus'",
    "start": "react-native start --port 3000",
    "test": "jest",
    "lint": "eslint .",
    "postinstall": "react-native-port-patcher --new-port 3000 --path node_modules/react-native"
  },
  "dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-port-patcher": "^1.0.4",
    "react-native-reanimated": "^1.7.0",
    "react-native-tab-view": "^2.13.0",
    "typescript": "^3.7.5"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "@testing-library/react-native": "^5.0.3",
    "babel-jest": "^24.9.0",
    "eslint": "^5.16.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "@testing-library/react-native",
    "setupFiles": [
      "react-native-gesture-handler/jestSetup.js",
      "./setupTests.js"
    ]
  }
}
```

setupTests.js
```javascript
// in the react-native-reanimated docs as the recommended way to mock this module.  Has to be done,
// otherwise other modules in the project fail spectacularly during tests.
jest.mock('react-native-reanimated', () => require('react-native-reanimated/mock'));
```

tests/App-test.js
```javascript
/**
 * @format
 */

import 'react-native';
import React from 'react';
import {App} from '../App';

// Note: test renderer must be required after react-native.
import {render} from '@testing-library/react-native';

it('renders correctly', () => {
  render(<App />);
});
```

Then `npm test` causes the error/warning output in the above screenshots.

https://github.com/frantjc/react-native-tab-view-issue

### What have you tried

I've tried to parse the Pager/TabView components' source to find where the source is using the mocked modules in a way that causes the issues and changing the mock implementations to no avail.

### Your Environment

| software                                     | version         |
| ----------------------------- | ------------ |
| ios or android                            | both              |
| react-native                               | 0.61.5           |
| react-native-tab-view              | 2.13.0           |
| react-native-gesture-handler | 1.5.3             |
| react-native-reanimated          | 1.7.0             |
| node                                            | 10.19.0         |
| npm or yarn                                | npm 6.13.7 |

**Comment by doomsower** [comment]
I was able to mock this:

```tsx
import React from 'react';
import { View } from 'react-native';

const MockPager = ({ children }: any) => {
  return children({
    position: 0,
    addListener: jest.fn(),
    removeListener: jest.fn(),
    jumpTo: jest.fn(),
    render: (children: any) => <View>{children}</View>,
  });
};

const getPager = (props: any) => <MockPager {...props} />;

export default getPager;
```

**Comment by frantjc** [comment]
@doomsower Thanks!! I'll give this a shot and report back here about how it works/any changes I need to make to it.

**Comment by Eldavid** [comment]
@doomsower How did you solve this issue?

**Comment by KoboBunny** [comment]
> I was able to mock this:
> 
> ```tsx
> import React from 'react';
> import { View } from 'react-native';
> 
> const MockPager = ({ children }: any) => {
>   return children({
>     position: 0,
>     addListener: jest.fn(),
>     removeListener: jest.fn(),
>     jumpTo: jest.fn(),
>     render: (children: any) => <View>{children}</View>,
>   });
> };
> 
> const getPager = (props: any) => <MockPager {...props} />;
> 
> export default getPager;
> ```

Thanks for the mock @doomsower !  How did you implement the mock?  I'm stuck on the same error and am not sure where to include the mock

**Comment by doomsower** [comment]
> Thanks for the mock @doomsower ! How did you implement the mock? I'm stuck on the same error and am not sure where to include the mock

MyTabs is multi-tab form to be tested.

`./MyTabs.tsx`:

```jsx
import getPager from './getPager';

//...

const MyTabs = () => {
  return (
    <Tab.Navigator
      {...props}
      pager={getPager}>
         {/*Whatever*/}
    </Tab.Navigator>
  );
};
```

`./getPager.tsx` (real pager):

```tsx
import { TabViewProps } from 'react-native-tab-view';

const getPager: TabViewProps<any>['renderPager'] | undefined = undefined;

export default getPager;
```

`./__mocks__/getPager.tsx` (mock pager):

```tsx
import React from 'react';
import { View } from 'react-native';

const MockPager = ({ children }: any) => {
  return children({
    position: 0,
    addListener: jest.fn(),
    removeListener: jest.fn(),
    jumpTo: jest.fn(),
    render: (childrn: any) => <View>{childrn}</View>,
  });
};

const getPager = (props: any) => <MockPager {...props} />;

export default getPager;
```

`./__tests__/form.tsx`:

```tsx
jest.mock('../getPager');

// tests that render MyTabs
```

**Comment by milesj** [comment]
This should fix it: https://github.com/satya164/react-native-tab-view/pull/1081
