### ISSUE TITLE
Android crash: Animated events must have event data.

### ISSUE THREAD

**Issue by valeriashpiner** [satya164/react-native-tab-view#976]
### Current behaviour

Android crashes when I scroll to the end of tabs. 
It happens all the time on Android.

You scroll to the end and then you try to scroll the last item more and more few times, but it's the last item so app just crashed after few scrolls.

### Expected behaviour

Android doesn't have crash when I scroll.

### Screenshots (if applicable)

<img width="500" alt="Screen Shot 2020-02-27 at 11 14 20 AM" src="https://user-images.githubusercontent.com/18754922/75462473-51a24200-5952-11ea-97d9-78005bb536b9.png">

It's only your library in my project which uses reanimated and react-native-gesture-handler together, and it happens on react-native-tab-view components. So I believe, it's related to your library. 

### What have you tried

I updated react-native-tab-view to 2.13.0. 
I updated reanimated to 1.7.0.
I put import 'react-native-gesture-handler' at the top of root file index.js.
Releated issue [here](https://github.com/react-navigation/react-navigation/issues/6403)

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | android
| react-native                 | 0.61.2
| react-native-tab-view        | 2.11.0 and 2.13.0
| react-native-gesture-handler | ^1.4.1
| react-native-reanimated      | ^1.2.0 and ^1.7.0
| node                         | 12.12.0
| npm or yarn                  | yarn

**Comment by valeriashpiner** [comment]
If it will help - it also crashed on you `example` from this repo. Probably, `react-native-gesture-handler` has an issue.
I think, maybe the problem in Paget.tsx

```  private handleGestureEvent = event([
    {
      nativeEvent: {
        translationX: this.gestureX,
        velocityX: this.velocityX,
        state: this.gestureState,
      },
    },
  ]);```

I would love to help more and try to spend more time on this. 
I will if I will have a chance.

**Comment by valeriashpiner** [comment]
This is also reproducible on `example` from this repository.

**Comment by valeriashpiner** [comment]
@ezechielk I fixed it **temporarily** in my fork: https://github.com/valeriashpiner/react-native-tab-view
It's one line change there.
You could try it. 
I checked it on a few real devices and it seems that everything works well.

**Comment by ezechielk** [comment]
Great ! Works like a charm thank you !
ᐧ

**Comment by anastely** [comment]
@valeriashpiner I don't use this library, And I got the same error 🤷‍♂️ Maybe related on `react-native-gesture-handler` So if you solve it, please tell me :))

**Comment by valeriashpiner** [comment]
> @valeriashpiner I don't use this library, And I got the same error 🤷‍♂️ Maybe related on `react-native-gesture-handler` So if you solve it, please tell me :))

You could use my fork: https://github.com/valeriashpiner/react-native-tab-view
I fixed it *temporarily*. 

 It's one line change there exactly in `PanGestureHandler` component.
 You could try it.
 I checked it on a few real devices and it seems that everything works well.

**Comment by valeriashpiner** [comment]
@anastely 

You could use my fork: https://github.com/valeriashpiner/react-native-tab-view if you need `react-native-tab-view`.
I fixed it **temporarily.**

It's one line change there exactly in `PanGestureHandler` component which is part of `react-native-gesture-handler`. You could try it.
I checked it on a few real devices and it seems that everything works well.

**Comment by anastely** [comment]
@valeriashpiner  Sadly I used `react-navigation-tabs` but I will give a try

**Comment by shehzabcodecraft** [comment]
@anastely Are you able to solve it? Please explain if you have done it.

**Comment by valeriashpiner** [comment]
@shehzabcodecraft you could use my fork, I fixed it there.

**Comment by osdnk** [comment]
https://github.com/osdnk/rntv-976

cannot repro. Please provide an example.

**Comment by valeriashpiner** [comment]
@osdnk I just reproduced it on your repo and recorded video. To reproduce you should scroll the last screen to the right side (to next screen which obviously not exists) and visa versa.
<img width="150" src="https://user-images.githubusercontent.com/18754922/76115585-6c119680-5fb6-11ea-9bb0-674fb6781cf8.gif" />

It will exist everywhere because it exists in the original example.

**Comment by osdnk** [comment]
What I'm doing wrong?

**Comment by osdnk** [comment]
https://streamable.com/tuwyc

**Comment by valeriashpiner** [comment]
It appears on the real device. It happened with me and also with another ppl in this thread. What the point of proving that you can't reproduce it if I already recorded video from your project that it exists there?

**Comment by osdnk** [comment]
I have no problem with saying that the bug exists. But I’d like to fix it as well stack trace is not sufficient for debugging

**Comment by valeriashpiner** [comment]
Okay, @osdnk, sorry for misunderstanding:

Steps to reproduce:
- Go to the last screen by scrolling left.
- At the last screen, keep scrolling left more and more (even if the next screen doesn't exist.)

Maybe @ezechielk can help to explain more.

**Comment by anastely** [comment]
@osdnk I'm facing the same [issue](https://github.com/react-navigation/react-navigation/issues/7722) but with react-navigation "MaterialTopTabNavigatore"

**Comment by shehzabdeveloper** [comment]
I defined swipeEnabled as false.. so this issue got a workaround

**Comment by lander854** [comment]
same problem

**Comment by EugeneDraitsev** [comment]
@osdnk It's reproduced by constantly swiping to the left on first tab or to the right on last tab, but I can reproduce it only on prod version of build. So would be nice if you can try to reproduce and maybe fix it

**Comment by melkayam92** [comment]
same here

**Comment by shehzabdeveloper** [comment]
> @osdnk It's reproduced by constantly swiping to the left on first tab or to the right on last tab, but I can reproduce it only on prod version of build. So would be nice if you can try to reproduce and maybe fix it

You can disable the swipe option. "swipeEnabled" component as false will solve the crash. But after that, you cant swipe between tabs. Instead, you need to tap on the options to open tabs.

**Comment by avlonder** [comment]
Hi, is there currently a workaround that still allows swiping between tabs? For example, is there a way to catch the erroneous swipes with react-native-gesture-handler? :)

**Comment by svenlombaert** [comment]
@avlonder This workaround works, and still allows swiping:
https://github.com/getdelta/react-native-gesture-handler/commit/311da062a679a81f6d3578cacb44c81aa29ede95

I copied it from another fork that fixed it on an older version of react-native-gesture-handler

**Comment by jakub-gonet** [comment]
Hi guys,
I reproduced this issue on example app running in production mode. However, the app is working when I run code in create-react-app with the newest versions of Reanimated and Gesture Handler.

@valeriashpiner, @melkayam92, @anastely, @EugeneDraitsev, @svenlombaert can you guys check if this issue still exists on Reanimated@1.7.1 and Gesture Handler@1.6.1?

**Comment by valeriashpiner** [comment]
@jakub-gonet oh, I am without android device now (it's not reproducible on a simulator). I hope someone here could help!

**Comment by svenlombaert** [comment]
I don't have an android device either, but I reproduced it on reanimated@1.7.0 and gesture-handler@1.6.0. From the commits I see in both patches, it would be highly unlikely it got fixed.

**Comment by 2788** [comment]
I reproduced it on reanimated@1.7.1 and gesture-handler@1.6.1.

**Comment by chgsilva** [comment]
i am still facing this issue, any news?

**Comment by raj-upadhyay** [comment]
I am still facing this issue reproduced in issue with react-native-reanimated@1.1.0, react-native-gesture-handler@1.3.0, and react-native-tab-view@2.5.0

**Comment by pradnesh-amin** [comment]
> I am still facing this issue reproduced in issue with react-native-reanimated@1.1.0, react-native-gesture-handler@1.3.0, and react-native-tab-view@2.5.0

Yes me too..

**Comment by drb1** [comment]
"react-native-gesture-handler": "1.6.1",
    "react-native-reanimated": "1.9.0",
    "react-native-tab-view": "^2.13.0",
still same issue

**Comment by jakub-gonet** [comment]
@chgsilva, @raj-upadhyay, @pradnesh-amin, @drb1 

this issue is probably related to gesture handler, would really appreciate some reproduction examples.

**Comment by sannajammeh** [comment]
As a temporary fix you can replace the pager component with an entirely native one: https://github.com/software-mansion-labs/react-native-tab-view-viewpager-adapter . Thus bypassing the gesture-handler itself.

**Comment by midoushitongtong** [comment]
> @chgsilva, @raj-upadhyay, @pradnesh-amin, @drb1
> 
> this issue is probably related to gesture handler, would really appreciate some reproduction examples.

hi!
Please try this snack.
You just have to slide normally to see the problem.
[https://snack.expo.io/@midoushitongtong/rntv-976-test](https://snack.expo.io/@midoushitongtong/rntv-976-test)

**Comment by jayzyaj** [comment]
any updates on this?

**Comment by leonimurilo** [comment]
Same issue here. I still did not get the pattern but I have two nested createMaterialTopTabNavigator

**Comment by rphlmr** [comment]
I reproduce on android 10 but not on 9 and lower. If it helps :'(

**Comment by hamidfzm** [comment]
This bug should be fixed in react native gesture handler. This is my patch package file in order to fix the android crash. Hope it will be a useful workaround until they fix it.
https://gist.github.com/hamidfzm/b85332b6d7408307a1e250b0f2db4d7f

**Comment by OsamaMukhtar** [comment]
Needs to be fixed. Same issue here

**Comment by ShahalKP** [comment]
+1. I hope I'll notice when they patch this.

**Comment by kamalpandey** [comment]
Same issue. Any workaround?
  
 ```
 "expo": "36",
  "react-native-gesture-handler": "~1.5.0",
  "react-native-reanimated": "~1.4.0",
  "react-native-tab-view": "2.15.0",
  "react-native-webview": "^7.0.5",
  "react-navigation": "^4.0.9",
  "react-navigation-stack": "^2.8.2",
  "react-navigation-tabs": "^2.9.0",
```

**Comment by kamalpandey** [comment]
> As a temporary fix you can replace the pager component with an entirely native one: https://github.com/software-mansion-labs/react-native-tab-view-viewpager-adapter . Thus bypassing the gesture-handler itself.

In IOS the keyboard opens and closes automatically but works fine if i remove it but for android I should add this as this is working. How should i deal with IOS?

[](https://github.com/osdnk/react-native-tab-view-viewpager-adapter/issues/17l)

**Comment by kamalpandey** [comment]
@sannajammeh 

In IOS the keyboard opens and closes automatically but works fine if i remove it but for android I should add this as this is working. How should i deal with IOS?

[More Info Here](https://github.com/osdnk/react-native-tab-view-viewpager-adapter/issues/17)

**Comment by aliceathens** [comment]
+1

**Comment by mchambaud** [comment]
+1 still happening

**Comment by c-goettert** [comment]
This issue is closed, but if I trace the [PR from gesture-handler ](software-mansion/react-native-gesture-handler#1171) correctly, it was first introduced in version 1.8, while react-native-tab-view currently uses 1.6. 
Are there any plans to update gesture-handler soon, to have the fix included? (Or did I misunderstand something?)

**Comment by HugoGresse** [comment]
you can specify the version yourself in the `package.json`

```
"react-native-gesture-handler": "1.9.0",
```

**Comment by jakub-gonet** [comment]
@c-goettert tab-view uses 1.6 but for development (in devDependencies section). RNGH version is actually ruled by your project dependency, as it's listed in [peer dependencies](https://github.com/satya164/react-native-tab-view/blob/main/package.json#L72).

**Comment by c-goettert** [comment]
@HugoGresse @jakub-gonet  thanks for pointing that out! I'll try update gesture handler then. :)

**Comment by Gogul-S** [comment]
> @c-goettert tab-view uses 1.6 but for development (in devDependencies section). RNGH version is actually ruled by your project dependency, as it's listed in [peer dependencies](https://github.com/satya164/react-native-tab-view/blob/main/package.json#L72).

@jakub-gonet Will updating gesture-handler version in package.json fix the crash in production also?

**Comment by jakub-gonet** [comment]
Yes, it'll fix this issue both in the development and release versions of your app.
