### ISSUE TITLE
Is it possible to swipe back to a previous page on the first tab?

### ISSUE THREAD

**Issue by wong2** [satya164/react-native-tab-view#979]
Say I have two pages: `Home` and `Settings`, and I'm using `react-navigation` for routing, which enables gesture to swipe back to Home page from Settings page.
But after adding tab view to the Settings page, I can't use gesture to go back anymore!
Is it possible to swipe back to `Home` page if I'm on the first tab?

if there's any way to do this, I'd like to work on a PR, but please let me know how it's possible

**Comment by rasulrukhilloev** [comment]
hi, you can create function which uses the .previousIndex prop of  and add this listener to componentDidMount
Example: 
`  onBackPress = () => {
    const { setTab, tabs } = this.props
    setTab(tabs.previousIndex)
    return true
  }

  componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', this.onBackPress)
  }`
Where setTab is located in store, it contains the state.  Im quite new to RN though, let me know if it works
