### ISSUE TITLE
Is it possible to have nested tabs with TabView. 

### ISSUE THREAD

**Issue by rasulrukhilloev** [satya164/react-native-tab-view#982]
### Code sample

For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |
| react-native                 |
| react-native-tab-view        |
| react-native-gesture-handler |
| react-native-reanimated      |
| node                         |
| npm or yarn                  |

**Comment by satya164** [comment]
It's not possible

**Comment by abhiburk** [comment]
is it not possible to have a main tab and then inside same tab in one card want to use new tab ?
