### ISSUE TITLE
[iOS] Difficulty to swipe between tabs 

### ISSUE THREAD

**Issue by jasonkw9** [satya164/react-native-tab-view#985]
### Current behaviour
Been searching over the internet but cant seem to find similar issue. I am facing the difficulty to swipe between tabs and it only happens on iOS. It's totally fine on android. Currently on iOS, it took 2 to 3 swipes for it to swipe to the next tab.

### Expected behaviour
It should swipe to next tab by one swipe only.

### Code sample

For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |
| react-native                 |
| react-native-tab-view        |
| react-native-gesture-handler |
| react-native-reanimated      |
| node                         |
| npm or yarn                  |

**Comment by Geoff-Ford** [comment]
I am also seeing the same issue on occasion and there doesn't appear to be a way to configure the sensitivity. For example the drawer navigator has a `minSwipeDistance` prop.

**Comment by Ronaldvdh-ISAAC** [comment]
I did not have this issue on iOS with version 2.15.2. After upgrading to 3.0.1 this issue came to light, which makes UX horrible on iOS which means i don't want to upgrade the package.
