### ISSUE TITLE
Tabs do not update when setting routes

### ISSUE THREAD

**Issue by FrankFundel** [satya164/react-native-tab-view#996]
### Current behaviour
When I update routes with `setState({routes: [...]});` the TabView does not update its tabs.

### Expected behaviour
TabView should dynamically update its routes.

### Code sample
```
          <TabView
            navigationState={{ index: pageIndex, routes }}
            renderScene={({ route }) => {
              switch (route.key) {
                case 'tracks':
                  return this.TracksRoute();
                case 'members':
                  return this.MembersRoute();
                case 'chat':
                  return this.ChatRoute();
                default:
                  return null;
              }
            }}
            renderTabBar={this.renderTabBar}
            onIndexChange={this.onIndexChange}
            swipeEnabled={isScrollEnable}
          />
```
```
    this.state = {
      pageIndex: 0,
      routes: [
        { key: 'tracks', title: 'TRACKS' },
      ],
    }
```
```
    this.state = {
      pageIndex: 0,
      routes: [
        { key: 'tracks', title: 'TRACKS' },
        { key: 'members', title: 'Members' },
      ],
    }
```

### Screenshots (if applicable)
-

### What have you tried
-

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | 13.3.1
| react-native                 | 0.61.5
| react-native-tab-view        | 2.11.0
| react-native-gesture-handler | 1.5.3
| react-native-reanimated      | 1.4.0
| node                         | v10.16.0
| npm or yarn                  | yarn version v1.21.1

**Comment by matapo** [comment]
I have resolved this problem by putting routes to redux store and reading them afterwards. 

`  const routes = useSelector((state) => state.routes);`
